#!/usr/bin/env python3
"""
Chippy: single-file, zero-dependency sandboxed agent harness.

Features:
- Strict canonical path enforcement (pathlib.resolve) to prevent directory traversal
- Native Python file operations (list, read, write, edit) with zero shell execution
- Human-in-the-loop diff approval for all writes/modifications
- AGENTS.md auto-discovery and OpenCode-style initial context payload
"""
# chippy v0.2.0 - self-contained, standard library only (Python 3.9+).
# Usage: python3 chippy.py -d <project-dir>   (API key from the OPENAI_API_KEY environment variable)
# Generated by scripts/build.py from chippy/. Do not edit here: change the modules and rebuild.

import argparse
import difflib
import fnmatch
import functools
import http.client
import inspect
import json
import os
import platform
import random
import stat
import sys
import tempfile
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


# ==================== chippy/__init__.py ====================

__version__ = "0.2.0"


# ==================== chippy/config.py ====================

DEFAULT_URL = os.getenv("LLM_BASE_URL", "https://api.openai.com/v1/chat/completions")
DEFAULT_MODEL = os.getenv("LLM_MODEL", "gpt-4o")
# The key is only read from the environment: CLI arguments leak into shell history and `ps`.
API_KEY_ENV = "OPENAI_API_KEY"

# Tool output limits keep a single call from flooding the model's context.
READ_MAX_LINES = 500
READ_MAX_CHARS = 256 * 1024
READ_MAX_LINE_CHARS = 2000
BINARY_SNIFF_BYTES = 8192
LIST_MAX_ENTRIES = 500
AGENTS_MD_MAX_CHARS = 64 * 1024

# Initial file map sent in the system prompt.
INVENTORY_MAX_FILES = 100
INVENTORY_MAX_DEPTH = 3
INVENTORY_SKIP_DIRS = frozenset({".git", "node_modules", "__pycache__", ".venv"})

# Diff lines shown before the approval prompt; the rest is available on request.
APPROVAL_DIFF_PREVIEW_LINES = 200

DEFAULT_MAX_STEPS = 25
HTTP_TIMEOUT_SECONDS = 120
HTTP_MAX_RETRIES = 4
HTTP_MAX_BACKOFF_SECONDS = 60


@dataclass(frozen=True)
class Settings:
    model: str
    url: str
    api_key: str = ""
    temperature: Optional[float] = None
    max_steps: int = DEFAULT_MAX_STEPS


# ==================== chippy/sandbox.py ====================

# Never readable or writable by the agent: hooks under .git/ run code on commit,
# and .git/config can hold credentials in remote URLs.
PROTECTED_DIR_NAMES = frozenset({".git"})

# Reads need no human approval and their contents go straight to the API, so likely
# secrets are refused. Patterns without "/" match the file name, others the relative path.
SECRET_FILE_PATTERNS = (
    ".env", ".env.*", "*.pem", "*.key", "*.p12", "*.pfx",
    "id_rsa*", "id_dsa*", "id_ecdsa*", "id_ed25519*",
    ".netrc", ".npmrc", ".pypirc",
)
SECRET_FILE_EXCEPTIONS = (".env.example", ".env.sample", ".env.template")

# Files that cause code to run later. Writes are still allowed, but the approval prompt flags them.
RISKY_WRITE_PATTERNS = (
    (".envrc", "direnv executes this when you enter the directory"),
    ("makefile", "make targets run shell commands"),
    ("gnumakefile", "make targets run shell commands"),
    ("package.json", "npm scripts run shell commands, including install hooks"),
    ("setup.py", "runs when the package is built or installed"),
    ("pyproject.toml", "configures build backends and hooks"),
    ("conftest.py", "pytest imports and runs this automatically"),
    (".pre-commit-config.yaml", "pre-commit runs these hooks on every commit"),
    (".vscode/*", "editor tasks and settings can run commands"),
    (".idea/*", "IDE run configurations can run commands"),
    (".github/workflows/*", "CI runs these with repository secrets"),
    (".gitlab-ci.yml", "CI runs these with repository secrets"),
    ("*.sh", "shell script"),
)


def resolve_scoped_path(rel_or_abs_path: str, workspace: Path) -> Path:
    """
    Resolves target path to its canonical form and verifies it strictly resides
    within the target workspace. Raises PermissionError on any escape attempt.
    """
    base = workspace.resolve()
    target = (base / rel_or_abs_path).resolve()

    # The canonical target path must be base or a descendant of base
    if target != base and base not in target.parents:
        raise PermissionError(
            f"Security Violation: Path '{rel_or_abs_path}' resolves to '{target}', "
            f"which escapes the designated workspace '{base}'."
        )
    return target


def _relative(target: Path, workspace: Path) -> Path:
    return target.relative_to(workspace.resolve())


def _matches(rel: Path, pattern: str) -> bool:
    # Case-insensitive: macOS and Windows filesystems treat ".GIT" and ".git" as the same directory.
    pattern = pattern.lower()
    subject = rel.as_posix() if "/" in pattern else rel.name
    return fnmatch.fnmatchcase(subject.lower(), pattern)


def is_protected(target: Path, workspace: Path) -> bool:
    return any(part.lower() in PROTECTED_DIR_NAMES for part in _relative(target, workspace).parts)


def is_secret(target: Path, workspace: Path) -> bool:
    rel = _relative(target, workspace)
    if any(_matches(rel, pattern) for pattern in SECRET_FILE_EXCEPTIONS):
        return False
    return any(_matches(rel, pattern) for pattern in SECRET_FILE_PATTERNS)


def check_listable(path: str, workspace: Path) -> Path:
    target = resolve_scoped_path(path, workspace)
    if is_protected(target, workspace):
        raise PermissionError(f"Access to '{path}' is blocked: version-control internals are off limits.")
    return target


def check_readable(path: str, workspace: Path) -> Path:
    target = check_listable(path, workspace)
    if is_secret(target, workspace):
        raise PermissionError(f"Access to '{path}' is blocked: it looks like a secrets file.")
    return target


def check_writable(path: str, workspace: Path) -> Path:
    return check_listable(path, workspace)


def write_warnings(target: Path, workspace: Path) -> list:
    """Reasons a write to `target` deserves extra scrutiny from the human approver."""
    rel = _relative(target, workspace)
    warnings = [reason for pattern, reason in RISKY_WRITE_PATTERNS if _matches(rel, pattern)]
    if is_secret(target, workspace):
        warnings.append("looks like a secrets file")
    return warnings


# ==================== chippy/terminal.py ====================

def sanitize(text) -> str:
    """
    Escapes control characters (ANSI escapes, carriage returns, bidi overrides) so
    model output cannot redraw the terminal or spoof the approval prompt.
    """
    out = []
    for ch in str(text):
        if ch in "\n\t" or ch.isprintable():
            out.append(ch)
            continue
        code = ord(ch)
        if code <= 0xFF:
            out.append(f"\\x{code:02x}")
        elif code <= 0xFFFF:
            out.append(f"\\u{code:04x}")
        else:
            out.append(f"\\U{code:08x}")
    return "".join(out)


def clip(text: str, limit: int) -> str:
    return text if len(text) <= limit else text[:limit] + "..."


# ==================== chippy/approval.py ====================

def _diff_lines(old_text: str, new_text: str, label: str) -> list:
    return list(difflib.unified_diff(
        old_text.splitlines(), new_text.splitlines(),
        fromfile=f"a/{label}", tofile=f"b/{label}", lineterm="",
    ))


def _print_diff(diff: list, limit=None) -> bool:
    """Prints the diff, returning True if it was cut short."""
    shown = diff if limit is None else diff[:limit]
    for line in shown:
        print(sanitize(line))
    if len(shown) < len(diff):
        print(f"... [{len(diff) - len(shown)} more diff lines]")
        return True
    return False


def request_write_approval(target: Path, workspace: Path, operation: str, old_text: str,
                           new_text: str, warnings: list, old_is_binary: bool = False) -> bool:
    """Shows the full change as a diff and asks the human to approve it."""
    label = target.relative_to(workspace.resolve()).as_posix()
    diff = _diff_lines("" if old_is_binary else old_text, new_text, label)
    old_lines = "binary" if old_is_binary else str(len(old_text.splitlines()))

    print("\n" + "=" * 60)
    print("[HUMAN APPROVAL REQUIRED: FILE WRITE]")
    print(f"Target Path: {sanitize(target)}")
    print(f"Operation  : {sanitize(operation)}")
    print(f"Size       : {len(new_text.encode('utf-8'))} bytes")
    print(f"Lines      : {old_lines} -> {len(new_text.splitlines())}")
    for warning in warnings:
        print(f"!! WARNING : {warning}")
    if old_is_binary:
        print("!! WARNING : the existing file is binary and will be replaced; diff is against an empty file")
    print("-" * 60)
    truncated = _print_diff(diff, APPROVAL_DIFF_PREVIEW_LINES)
    print("=" * 60)

    prompt = "Allow write operation? [y/N" + ("/v = view full diff" if truncated else "") + "]: "
    while True:
        try:
            decision = input(prompt).strip().lower()
        except EOFError:
            return False
        if decision in ("y", "yes"):
            return True
        if decision == "v" and truncated:
            _print_diff(diff)
            continue
        return False


# ==================== chippy/tools.py ====================

def _tool_errors(func):
    """Turns exceptions into tool results so a failing tool never ends the session."""
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except PermissionError as pe:
            return {"status": "denied", "message": str(pe)}
        except Exception as e:
            return {"status": "error", "message": f"{type(e).__name__}: {e}"}
    return wrapper


def _as_int(value, name: str) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        raise ValueError(f"'{name}' must be an integer, got {value!r}") from None


def _as_bool(value) -> bool:
    if isinstance(value, str):
        return value.strip().lower() in ("true", "1", "yes")
    return bool(value)


def _is_binary(path: Path) -> bool:
    with open(path, "rb") as f:
        return b"\x00" in f.read(BINARY_SNIFF_BYTES)


def _read_text(path: Path, strict: bool) -> tuple:
    """
    Returns (text, newline). Text always uses '\\n' line endings; `newline` is the
    file's original ending so writes can restore it.
    """
    raw = path.read_bytes()
    newline = "\r\n" if b"\r\n" in raw else "\n"
    text = raw.decode("utf-8", errors="strict" if strict else "replace")
    return text.replace("\r\n", "\n"), newline


def _default_file_mode() -> int:
    umask = os.umask(0)
    os.umask(umask)
    return 0o666 & ~umask


def _atomic_write(target: Path, text: str, newline: str) -> None:
    """Writes via a temp file + rename so an interrupted write never leaves a half-written file."""
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = stat.S_IMODE(target.stat().st_mode) if target.exists() else _default_file_mode()
    fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline=newline) as f:
            f.write(text)
        os.chmod(tmp, mode)
        os.replace(tmp, target)
    except BaseException:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass
        raise


def _iter_lines(f, max_chars: int):
    """Yields (line, clipped), capping each line at max_chars without loading over-long lines into memory."""
    while True:
        line = f.readline(max_chars)
        if not line:
            return
        clipped = False
        if len(line) >= max_chars and not line.endswith(("\n", "\r")):
            ending = ""
            rest = f.readline(max_chars)
            while rest:
                if rest.endswith(("\n", "\r")):
                    ending = "\n"
                    break
                rest = f.readline(max_chars)
            clipped = True
            line = f"{line}... [line clipped at {max_chars} chars]{ending}"
        yield line.replace("\r\n", "\n"), clipped


# ==========================================
# Tools
# ==========================================

@_tool_errors
def tool_list_directory(workspace: Path, directory_path: str = ".") -> dict:
    """Lists entries inside a specified directory relative to workspace root."""
    target = check_listable(directory_path or ".", workspace)
    if not target.exists():
        return {"status": "error", "message": f"Directory '{directory_path}' does not exist."}
    if not target.is_dir():
        return {"status": "error", "message": f"Path '{directory_path}' is not a directory."}

    children = sorted(target.iterdir())
    entries = []
    for entry in children[:LIST_MAX_ENTRIES]:
        item = {"name": entry.name}
        if entry.is_symlink():
            item["is_symlink"] = True
            try:
                resolve_scoped_path(str(entry), workspace)
            except PermissionError:
                # Don't stat it: that would leak metadata about files outside the workspace.
                item["outside_workspace"] = True
                entries.append(item)
                continue
        try:
            st = entry.stat()
        except OSError:
            item["error"] = "unreadable (broken symlink?)"
            entries.append(item)
            continue
        is_dir = stat.S_ISDIR(st.st_mode)
        item["is_dir"] = is_dir
        item["size_bytes"] = None if is_dir else st.st_size
        entries.append(item)

    result = {"status": "success", "entries": entries}
    if len(children) > LIST_MAX_ENTRIES:
        result["truncated"] = True
        result["note"] = f"Showing the first {LIST_MAX_ENTRIES} of {len(children)} entries."
    return result


@_tool_errors
def tool_read_file(workspace: Path, file_path: str, offset=1, limit=READ_MAX_LINES) -> dict:
    """Safely reads a window of lines from a text file within the workspace."""
    target = check_readable(file_path, workspace)
    if not target.exists():
        return {"status": "error", "message": f"File '{file_path}' does not exist."}
    if not target.is_file():
        return {"status": "error", "message": f"Path '{file_path}' is not a regular file."}
    offset = _as_int(offset, "offset")
    if offset < 1:
        return {"status": "error", "message": "'offset' must be 1 or greater."}
    limit = max(1, min(_as_int(limit, "limit"), READ_MAX_LINES))
    if _is_binary(target):
        return {"status": "error", "message": f"File '{file_path}' appears to be binary."}

    lines, chars, clipped_count, line_no, has_more = [], 0, 0, 0, False
    with open(target, "r", encoding="utf-8", errors="replace", newline="") as f:
        for line_no, (line, clipped) in enumerate(_iter_lines(f, READ_MAX_LINE_CHARS), start=1):
            if line_no < offset:
                continue
            if len(lines) >= limit or chars + len(line) > READ_MAX_CHARS:
                has_more = True
                break
            lines.append(line)
            chars += len(line)
            clipped_count += clipped

    if not lines and offset > 1:
        return {"status": "error", "message": f"'offset' {offset} is past the end of the file ({line_no} lines)."}

    end_line = offset + len(lines) - 1
    result = {
        "status": "success",
        "content": "".join(lines),
        "start_line": offset,
        "end_line": end_line,
        "has_more": has_more,
    }
    notes = []
    if has_more:
        result["next_offset"] = end_line + 1
        notes.append(f"Showing lines {offset}-{end_line}. Call read_file with offset={end_line + 1} to continue.")
    if clipped_count:
        notes.append(f"{clipped_count} over-long line(s) were clipped to {READ_MAX_LINE_CHARS} characters.")
    if not notes:
        notes.append("Full file content" if offset == 1 else "End of file")
    result["note"] = " ".join(notes)
    return result


@_tool_errors
def tool_write_file(workspace: Path, file_path: str, content: str) -> dict:
    """Prompts human approval (with a diff) before creating or overwriting a file."""
    target = check_writable(file_path, workspace)
    if target.is_dir():
        return {"status": "error", "message": f"Path '{file_path}' is a directory."}
    if not isinstance(content, str):
        return {"status": "error", "message": "'content' must be a string."}

    exists = target.exists()
    old_text, newline, old_is_binary = "", "\n", False
    if exists:
        old_is_binary = _is_binary(target)
        if not old_is_binary:
            old_text, newline = _read_text(target, strict=False)
    new_text = content.replace("\r\n", "\n")
    if exists and not old_is_binary and new_text == old_text:
        return {"status": "success", "message": f"No changes: '{file_path}' already has this content."}

    approved = request_write_approval(
        target, workspace, "Overwrite" if exists else "Create new file",
        old_text, new_text, write_warnings(target, workspace), old_is_binary=old_is_binary,
    )
    if not approved:
        return {"status": "denied", "message": "File write rejected by human supervisor."}

    _atomic_write(target, new_text, newline)
    return {"status": "success", "message": f"Wrote {len(new_text.splitlines())} lines to {file_path}."}


@_tool_errors
def tool_edit_file(workspace: Path, file_path: str, old_string: str, new_string: str, replace_all=False) -> dict:
    """Replaces an exact, unique snippet in an existing file, after human approval."""
    # Readable check too: match/no-match errors would otherwise reveal the contents of secret files.
    target = check_readable(file_path, workspace)
    check_writable(file_path, workspace)
    if not target.is_file():
        return {"status": "error", "message": f"File '{file_path}' does not exist. Use write_file to create it."}
    if not isinstance(old_string, str) or not isinstance(new_string, str):
        return {"status": "error", "message": "'old_string' and 'new_string' must be strings."}
    if not old_string:
        return {"status": "error", "message": "'old_string' must not be empty. Use write_file to create or replace whole files."}
    if old_string == new_string:
        return {"status": "error", "message": "'old_string' and 'new_string' are identical."}
    if _is_binary(target):
        return {"status": "error", "message": f"File '{file_path}' appears to be binary."}
    try:
        text, newline = _read_text(target, strict=True)
    except UnicodeDecodeError:
        return {"status": "error", "message": f"File '{file_path}' is not valid UTF-8; editing it could corrupt it."}

    old = old_string.replace("\r\n", "\n")
    new = new_string.replace("\r\n", "\n")
    count = text.count(old)
    if count == 0:
        return {"status": "error", "message": "'old_string' was not found. Read the file again and copy the text exactly, including whitespace."}
    replace_all = _as_bool(replace_all)
    if count > 1 and not replace_all:
        return {"status": "error", "message": f"'old_string' appears {count} times. Include more surrounding context to make it unique, or set replace_all=true."}

    replaced = count if replace_all else 1
    new_text = text.replace(old, new, -1 if replace_all else 1)
    approved = request_write_approval(
        target, workspace, f"Edit ({replaced} replacement{'s' if replaced > 1 else ''})",
        text, new_text, write_warnings(target, workspace),
    )
    if not approved:
        return {"status": "denied", "message": "File edit rejected by human supervisor."}

    _atomic_write(target, new_text, newline)
    return {"status": "success", "message": f"Replaced {replaced} occurrence(s) in {file_path}."}


# ==========================================
# Registry: the single source of truth for tool names, schemas and handlers
# ==========================================

_REGISTRY = (
    (tool_list_directory, {
        "name": "list_directory",
        "description": f"List files and subdirectories within a given relative folder path (up to {LIST_MAX_ENTRIES} entries).",
        "parameters": {
            "type": "object",
            "properties": {
                "directory_path": {
                    "type": "string",
                    "description": "Relative directory path. Use '.' or '' for root.",
                },
            },
            "required": ["directory_path"],
        },
    }),
    (tool_read_file, {
        "name": "read_file",
        "description": (
            f"Read a UTF-8 text file, at most {READ_MAX_LINES} lines per call. "
            "If the result has has_more=true, call again with offset=next_offset to read the rest. "
            "Always read the whole file before rewriting it with write_file."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Relative path of the file to inspect."},
                "offset": {"type": "integer", "description": "1-based line number to start from. Defaults to 1."},
                "limit": {"type": "integer", "description": f"Maximum lines to return (1-{READ_MAX_LINES}). Defaults to {READ_MAX_LINES}."},
            },
            "required": ["file_path"],
        },
    }),
    (tool_write_file, {
        "name": "write_file",
        "description": (
            "Create a new file, or replace an existing file's entire content. Requires human approval. "
            "Prefer edit_file for changes to existing files."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Relative path of the target file to create or replace."},
                "content": {"type": "string", "description": "The exact full text content to write."},
            },
            "required": ["file_path", "content"],
        },
    }),
    (tool_edit_file, {
        "name": "edit_file",
        "description": (
            "Replace an exact snippet of an existing file with new text. Requires human approval. "
            "old_string must match the file exactly (including whitespace) and be unique unless replace_all is true."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Relative path of the file to edit."},
                "old_string": {"type": "string", "description": "Exact text to replace."},
                "new_string": {"type": "string", "description": "Replacement text."},
                "replace_all": {"type": "boolean", "description": "Replace every occurrence instead of requiring a unique match."},
            },
            "required": ["file_path", "old_string", "new_string"],
        },
    }),
)

TOOL_HANDLERS = {schema["name"]: handler for handler, schema in _REGISTRY}
TOOLS = [{"type": "function", "function": schema} for _, schema in _REGISTRY]


def dispatch_tool(name: str, raw_arguments, workspace: Path) -> dict:
    """Runs one model tool call. Bad names or arguments become error results the model can correct."""
    handler = TOOL_HANDLERS.get(name)
    if handler is None:
        return {"status": "error", "message": f"Unknown tool: {name!r}. Available tools: {', '.join(TOOL_HANDLERS)}."}

    if isinstance(raw_arguments, dict):
        args = raw_arguments
    else:
        try:
            args = json.loads(raw_arguments) if raw_arguments else {}
        except (TypeError, ValueError) as e:
            return {"status": "error", "message": f"Arguments are not valid JSON ({e}). Retry with a JSON object."}
    if not isinstance(args, dict):
        return {"status": "error", "message": "Arguments must be a JSON object."}

    try:
        inspect.signature(handler).bind(workspace, **args)
    except TypeError as e:
        return {"status": "error", "message": f"Invalid arguments for {name}: {e}"}
    return handler(workspace, **args)


# ==================== chippy/context.py ====================

def load_agents_md(workspace: Path) -> tuple:
    """Returns (status for the banner, rules text for the prompt)."""
    # Goes through the sandbox: a symlinked AGENTS.md must not pull files from outside the workspace.
    try:
        path = check_readable("AGENTS.md", workspace)
    except PermissionError as e:
        return f"Ignored ({e})", "None provided."
    if not path.is_file():
        return "None", "None provided."
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return f"Unreadable ({e})", f"Error reading AGENTS.md: {e}"
    if len(text) > AGENTS_MD_MAX_CHARS:
        text = text[:AGENTS_MD_MAX_CHARS] + "\n... [AGENTS.md truncated]"
    return "Detected", text


def build_inventory(workspace: Path) -> list:
    """Sorted file map (depth-limited, capped) so the prompt is identical across runs."""
    base = workspace.resolve()
    files = []
    for cur_root, dirs, names in os.walk(base):
        rel = Path(cur_root).relative_to(base)
        if len(rel.parts) < INVENTORY_MAX_DEPTH:
            dirs[:] = sorted(d for d in dirs if d not in INVENTORY_SKIP_DIRS)
        else:
            dirs[:] = []
        for name in sorted(names):
            files.append((rel / name).as_posix())
            if len(files) > INVENTORY_MAX_FILES:
                return files[:INVENTORY_MAX_FILES] + ["... [truncated]"]
    return files


def build_system_context(workspace: Path) -> tuple:
    """Returns (system prompt, AGENTS.md status)."""
    agents_status, agents_rules = load_agents_md(workspace)

    payload = {
        "agent_environment": {
            "os": platform.system(),
            "working_directory": str(workspace.resolve()),
            "isolation_mode": "No shell access; file tools are confined to the workspace",
        },
        "workspace_inventory": {
            "root_folder": workspace.name,
            "visible_files": build_inventory(workspace),
        },
        "agents_md_rules": agents_rules,
        "operating_constraints": [
            "You CANNOT execute terminal or shell commands (no bash, no powershell).",
            f"You only have access to these tools: {', '.join(TOOL_HANDLERS)}.",
            "All paths must be relative to the scoped workspace.",
            "Any path referencing parent directories outside the workspace will trigger a hard security denial.",
            ".git/ and likely secrets files (.env, private keys) are off limits.",
            f"read_file returns at most {READ_MAX_LINES} lines per call; page through longer files with 'offset' before changing them.",
            "Prefer edit_file for changes to existing files; use write_file to create files or replace them entirely.",
            "Every write is shown to a human as a diff and may be rejected.",
            "Follow all conventions defined in 'agents_md_rules'.",
        ],
    }

    prompt = (
        "You are an engineering assistant working in a sandboxed directory environment.\n"
        "Here is your initialization context payload:\n\n"
        "```json\n"
        + json.dumps(payload, indent=2) +
        "\n```"
    )
    return prompt, agents_status


# ==================== chippy/llm.py ====================

RETRYABLE_STATUS_CODES = frozenset({408, 409, 425, 429, 500, 502, 503, 504})


class LLMError(Exception):
    """The API call failed and retrying will not help. The conversation is left intact."""


def _backoff_delay(attempt: int, retry_after=None) -> float:
    if retry_after:
        try:
            return min(float(retry_after), HTTP_MAX_BACKOFF_SECONDS)
        except ValueError:
            pass  # HTTP-date form; fall back to exponential backoff
    return min(2 ** attempt, HTTP_MAX_BACKOFF_SECONDS) * (0.5 + random.random() / 2)


def _post_with_retries(url: str, body: bytes, headers: dict) -> bytes:
    for attempt in range(HTTP_MAX_RETRIES + 1):
        retry_after = None
        try:
            req = urllib.request.Request(url, data=body, headers=headers, method="POST")
            with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT_SECONDS) as resp:
                return resp.read()
        except urllib.error.HTTPError as e:
            detail = e.read().decode("utf-8", errors="replace")[:2000]
            if e.code not in RETRYABLE_STATUS_CODES or attempt == HTTP_MAX_RETRIES:
                raise LLMError(f"API error {e.code}: {detail}") from e
            reason = f"HTTP {e.code}"
            retry_after = e.headers.get("Retry-After") if e.headers else None
        except (OSError, http.client.HTTPException) as e:  # URLError, timeouts, dropped connections
            detail = getattr(e, "reason", None) or e
            if attempt == HTTP_MAX_RETRIES:
                raise LLMError(f"Network error: {detail}") from e
            reason = f"network error: {detail}"
        delay = _backoff_delay(attempt, retry_after)
        print(f"[{reason}] retrying in {delay:.1f}s ({attempt + 1}/{HTTP_MAX_RETRIES})", file=sys.stderr)
        time.sleep(delay)
    raise AssertionError("unreachable")


def _parse_response(raw: bytes) -> dict:
    try:
        data = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, ValueError) as e:
        raise LLMError(f"API returned invalid JSON: {e}") from e
    if isinstance(data, dict) and data.get("error"):
        raise LLMError(f"API error: {data['error']}")
    try:
        message = data["choices"][0]["message"]
    except (KeyError, IndexError, TypeError):
        raise LLMError(f"Unexpected API response: {str(data)[:500]}") from None
    if not isinstance(message, dict):
        raise LLMError(f"Unexpected API response: {str(data)[:500]}")
    return message


def call_llm_api(messages: list, tools: list, settings: Settings) -> dict:
    """Sends the conversation and returns the assistant message. Raises LLMError on failure."""
    payload = {
        "model": settings.model,
        "messages": messages,
        "tools": tools,
        "tool_choice": "auto",
    }
    # Some models (e.g. reasoning models) reject temperature, so it is only sent when set.
    if settings.temperature is not None:
        payload["temperature"] = settings.temperature
    headers = {"Content-Type": "application/json"}
    if settings.api_key:
        headers["Authorization"] = f"Bearer {settings.api_key}"

    raw = _post_with_retries(settings.url, json.dumps(payload).encode("utf-8"), headers)
    return _parse_response(raw)


# ==================== chippy/agent.py ====================

CANCELLED_RESULT = {"status": "cancelled", "message": "Not run: the user interrupted this turn."}


def _tool_message(call: dict, result: dict) -> dict:
    return {
        "role": "tool",
        "tool_call_id": call.get("id"),
        "name": (call.get("function") or {}).get("name") or "",
        "content": json.dumps(result),
    }


def run_turn(messages: list, workspace: Path, settings: Settings) -> None:
    """
    Alternates model calls and tool calls until the model answers without tools,
    or the step limit is reached. On KeyboardInterrupt every tool call the model
    already requested gets a result, so the history stays valid for the next request.
    """
    for _ in range(settings.max_steps):
        response_msg = call_llm_api(messages, TOOLS, settings)
        messages.append(response_msg)

        content = response_msg.get("content") or ""
        tool_calls = response_msg.get("tool_calls") or []
        if not tool_calls:
            print(f"\nAgent > {sanitize(content) or '(no response)'}\n")
            return
        if content:
            print(f"\nAgent > {sanitize(content)}\n")

        for index, call in enumerate(tool_calls):
            function = call.get("function") or {}
            name = function.get("name") or ""
            raw_args = function.get("arguments")
            print(f"[Tool Call] {sanitize(name)}({sanitize(clip(str(raw_args), 200))})")
            try:
                result = dispatch_tool(name, raw_args, workspace)
            except KeyboardInterrupt:
                for pending in tool_calls[index:]:
                    messages.append(_tool_message(pending, CANCELLED_RESULT))
                raise
            if result.get("status") != "success":
                print(f"  -> {result.get('status')}: {sanitize(clip(str(result.get('message', '')), 200))}")
            messages.append(_tool_message(call, result))

    print(f"\n[Stopped] Reached the limit of {settings.max_steps} steps for one request. "
          "Send another message to let the agent continue.\n")


def _discard_unanswered(messages: list) -> bool:
    """Drops the user's message if nothing happened after it, so retrying doesn't send it twice."""
    if messages and messages[-1].get("role") == "user":
        messages.pop()
        return True
    return False


def run_agent(workspace: Path, settings: Settings) -> None:
    system_prompt, agents_status = build_system_context(workspace)
    messages = [{"role": "system", "content": system_prompt}]

    print("=" * 60)
    print(f"Directory Sandbox : {workspace.resolve()}")
    print("Shell Disabled    : True (Pure Python file APIs only)")
    print(f"AGENTS.md         : {agents_status}")
    print(f"Model             : {settings.model}")
    print("=" * 60 + "\n")

    while True:
        try:
            user_input = input("You > ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nExiting.")
            break

        if not user_input:
            continue
        if user_input.lower() in ("exit", "quit"):
            break

        messages.append({"role": "user", "content": user_input})
        try:
            run_turn(messages, workspace, settings)
        except KeyboardInterrupt:
            print("\n[Interrupted]")
        except LLMError as e:
            print(f"\n[Error] {e}", file=sys.stderr)
        else:
            continue
        if _discard_unanswered(messages):
            print("Your last message was not sent; enter it again to retry.\n")
        else:
            print("Progress so far is kept; send a message to continue.\n")


# ==================== chippy/__main__.py ====================

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="chippy",
        description="Zero-dependency Sandboxed Agent Runner",
        epilog=f"The API key is read from the {API_KEY_ENV} environment variable.",
    )
    parser.add_argument("-d", "--dir", default=".", help="Target directory to lock the harness to.")
    parser.add_argument("-m", "--model", default=DEFAULT_MODEL, help="Model name.")
    parser.add_argument("--url", default=DEFAULT_URL, help="Chat completions endpoint URL.")
    parser.add_argument("--temperature", type=float, default=None,
                        help="Sampling temperature. Omitted from requests when not set.")
    parser.add_argument("--max-steps", type=int, default=DEFAULT_MAX_STEPS,
                        help="Maximum model calls per message before the agent pauses.")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")

    args = parser.parse_args(argv)
    if args.max_steps < 1:
        parser.error("--max-steps must be at least 1")

    target_dir = Path(args.dir).resolve()
    if not target_dir.is_dir():
        print(f"Error: Scoped folder '{target_dir}' does not exist.", file=sys.stderr)
        return 1

    settings = Settings(
        model=args.model,
        url=args.url,
        api_key=os.getenv(API_KEY_ENV, ""),
        temperature=args.temperature,
        max_steps=args.max_steps,
    )
    run_agent(target_dir, settings)
    return 0


if __name__ == "__main__":
    sys.exit(main())
