#!/usr/bin/env python3
"""
Chippy: single-file, zero-dependency sandboxed agent harness.

Features:
- Strict canonical path enforcement (pathlib.resolve) to prevent directory traversal
- Native Python file operations (list, read, write, edit) with zero shell execution
- Human-in-the-loop diff approval for all writes/modifications
- AGENTS.md auto-discovery and OpenCode-style initial context payload
"""
# chippy v0.2.0 - self-contained, standard library only (Python 3.9+).
# Usage: python3 chippy.py -d <project-dir>   (API key from the OPENAI_API_KEY environment variable)
# Generated by scripts/build.py from chippy/. Do not edit here: change the modules and rebuild.

import argparse
import dataclasses
import difflib
import fnmatch
import functools
import http.client
import inspect
import json
import os
import platform
import random
import re
import stat
import sys
import tempfile
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ==================== chippy/__init__.py ====================

__version__ = "0.2.0"


# ==================== chippy/config.py ====================

DEFAULT_URL = os.getenv("LLM_BASE_URL", "https://api.openai.com/v1/chat/completions")
DEFAULT_MODEL = os.getenv("LLM_MODEL", "gpt-4o")
# Empty means the explore sub-agent uses the main model.
DEFAULT_EXPLORE_MODEL = os.getenv("LLM_EXPLORE_MODEL", "")
# The key is only read from the environment: CLI arguments leak into shell history and `ps`.
API_KEY_ENV = "OPENAI_API_KEY"

# Tool output limits keep a single call from flooding the model's context.
READ_MAX_LINES = 500
READ_MAX_CHARS = 256 * 1024
READ_MAX_LINE_CHARS = 2000
BINARY_SNIFF_BYTES = 8192
LIST_MAX_ENTRIES = 500
SEARCH_MAX_MATCHES = 100
SEARCH_MAX_FILES = 5000
SEARCH_MAX_FILE_BYTES = 1024 * 1024
SEARCH_MAX_LINE_CHARS = 300
SEARCH_MAX_CONTEXT_LINES = 5

# AGENTS.md up to this size goes into the prompt verbatim; longer files are sent as an outline.
AGENTS_MD_INLINE_CHARS = 8 * 1024

# Initial file map sent in the system prompt.
INVENTORY_MAX_FILES = 100
INVENTORY_MAX_DEPTH = 3
# Skipped by the inventory and by search_files.
WALK_SKIP_DIRS = frozenset({".git", "node_modules", "__pycache__", ".venv"})

# Elision: tool results at least ELIDE_MIN_CHARS long, and string arguments of tool calls
# (write_file content, edit_file strings) at least ELIDE_ARG_MIN_CHARS long, become short stubs.
ELIDE_MIN_CHARS = 1000
ELIDE_ARG_MIN_CHARS = 300

# Context window management. Sizes are API-reported prompt tokens when available,
# otherwise estimated at CHARS_PER_TOKEN characters per token.
DEFAULT_CONTEXT_LIMIT = 128_000
MIN_CONTEXT_LIMIT = 4_000
CHARS_PER_TOKEN = 4
COMPACT_TRIGGER_RATIO = 0.8     # auto-compact once the conversation reaches this share of the limit
COMPACT_TARGET_RATIO = 0.5      # summarize if eliding alone doesn't get it below this share
COMPACT_KEEP_STEPS = 2          # the latest model steps are always kept verbatim
COMPACT_SUMMARY_INPUT_RATIO = 0.5
COMPACT_TRANSCRIPT_ARG_CHARS = 300
COMPACT_TRANSCRIPT_RESULT_CHARS = 1500

# Explore sub-agent limits.
EXPLORE_MODES = ("auto", "always", "never")
EXPLORE_READ_MAX_LINES = 200
EXPLORE_CONTEXT_RATIO = 0.5     # the explorer must report once its own context reaches this share
EXPLORE_SNIPPET_MAX_LINES = 80

# Diff lines shown before the approval prompt; the rest is available on request.
APPROVAL_DIFF_PREVIEW_LINES = 200

DEFAULT_MAX_STEPS = 25
DEFAULT_EXPLORE_MAX_STEPS = 15
HTTP_TIMEOUT_SECONDS = 120
HTTP_MAX_RETRIES = 4
HTTP_MAX_BACKOFF_SECONDS = 60


@dataclass(frozen=True)
class Settings:
    model: str
    url: str
    api_key: str = ""
    temperature: Optional[float] = None
    max_steps: int = DEFAULT_MAX_STEPS
    explore_model: str = ""
    explore_max_steps: int = DEFAULT_EXPLORE_MAX_STEPS
    explore_mode: str = "auto"
    context_limit: int = DEFAULT_CONTEXT_LIMIT
    log_path: str = ""


# ==================== chippy/llm.py ====================

RETRYABLE_STATUS_CODES = frozenset({408, 409, 425, 429, 500, 502, 503, 504})
# How OpenAI-compatible servers word "the prompt is larger than the context window".
CONTEXT_ERROR_MARKERS = (
    "context_length_exceeded", "maximum context length", "context length", "context window",
    "too many tokens", "prompt is too long", "input is too long", "reduce the length",
)


class LLMError(Exception):
    """The API call failed and retrying will not help. The conversation is left intact."""


class ContextLengthError(LLMError):
    """The request did not fit in the model's context window."""


def estimate_tokens(value) -> int:
    """Rough token count for messages or tool schemas, for when the API reports none."""
    return len(json.dumps(value, ensure_ascii=False)) // CHARS_PER_TOKEN


def _backoff_delay(attempt: int, retry_after=None) -> float:
    if retry_after:
        try:
            return min(float(retry_after), HTTP_MAX_BACKOFF_SECONDS)
        except ValueError:
            pass  # HTTP-date form; fall back to exponential backoff
    return min(2 ** attempt, HTTP_MAX_BACKOFF_SECONDS) * (0.5 + random.random() / 2)


def _post_with_retries(url: str, body: bytes, headers: dict) -> bytes:
    for attempt in range(HTTP_MAX_RETRIES + 1):
        retry_after = None
        try:
            req = urllib.request.Request(url, data=body, headers=headers, method="POST")
            with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT_SECONDS) as resp:
                return resp.read()
        except urllib.error.HTTPError as e:
            detail = e.read().decode("utf-8", errors="replace")[:2000]
            if e.code in (400, 413) and any(marker in detail.lower() for marker in CONTEXT_ERROR_MARKERS):
                raise ContextLengthError(f"API error {e.code}: {detail}") from e
            if e.code not in RETRYABLE_STATUS_CODES or attempt == HTTP_MAX_RETRIES:
                raise LLMError(f"API error {e.code}: {detail}") from e
            reason = f"HTTP {e.code}"
            retry_after = e.headers.get("Retry-After") if e.headers else None
        except (OSError, http.client.HTTPException) as e:  # URLError, timeouts, dropped connections
            detail = getattr(e, "reason", None) or e
            if attempt == HTTP_MAX_RETRIES:
                raise LLMError(f"Network error: {detail}") from e
            reason = f"network error: {detail}"
        delay = _backoff_delay(attempt, retry_after)
        print(f"[{reason}] retrying in {delay:.1f}s ({attempt + 1}/{HTTP_MAX_RETRIES})", file=sys.stderr)
        time.sleep(delay)
    raise AssertionError("unreachable")


def _parse_response(raw: bytes) -> tuple:
    """Returns (assistant message, usage dict; empty when the API reports none)."""
    try:
        data = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, ValueError) as e:
        raise LLMError(f"API returned invalid JSON: {e}") from e
    if isinstance(data, dict) and data.get("error"):
        raise LLMError(f"API error: {data['error']}")
    try:
        message = data["choices"][0]["message"]
    except (KeyError, IndexError, TypeError):
        raise LLMError(f"Unexpected API response: {str(data)[:500]}") from None
    if not isinstance(message, dict):
        raise LLMError(f"Unexpected API response: {str(data)[:500]}")
    usage = data.get("usage")
    return message, usage if isinstance(usage, dict) else {}


def _log_call(settings: Settings, source: str, messages: list, usage: dict) -> None:
    """Appends one JSON line per model call to settings.log_path, for comparing runs."""
    if not settings.log_path:
        return
    record = {
        "time": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "source": source,
        "model": settings.model,
        "messages": len(messages),
        "usage": usage,
    }
    try:
        with open(settings.log_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\n")
    except OSError as e:
        print(f"[Log] Could not write {settings.log_path}: {e}", file=sys.stderr)


def call_llm_api(messages: list, tools: list, settings: Settings, tool_choice="auto", source: str = "main") -> tuple:
    """
    Sends the conversation and returns (assistant message, usage dict). When the API
    reports no usage, the dict holds 'estimated_prompt_tokens' instead. `source` labels
    the call in the log. Raises LLMError (ContextLengthError if the prompt was too big).
    """
    payload = {"model": settings.model, "messages": messages}
    # Servers reject tool_choice without tools.
    if tools:
        payload["tools"] = tools
        payload["tool_choice"] = tool_choice
    # Some models (e.g. reasoning models) reject temperature, so it is only sent when set.
    if settings.temperature is not None:
        payload["temperature"] = settings.temperature
    headers = {"Content-Type": "application/json"}
    if settings.api_key:
        headers["Authorization"] = f"Bearer {settings.api_key}"

    raw = _post_with_retries(settings.url, json.dumps(payload).encode("utf-8"), headers)
    message, usage = _parse_response(raw)
    if not usage:
        usage = {"estimated_prompt_tokens": estimate_tokens(messages) + estimate_tokens(tools)}
    _log_call(settings, source, messages, usage)
    return message, usage


def token_count(value) -> int:
    return value if isinstance(value, int) and not isinstance(value, bool) and value > 0 else 0


def prompt_size(usage: dict) -> int:
    """The prompt's size in tokens: as reported, or estimated when the API reported nothing."""
    return token_count(usage.get("prompt_tokens")) or token_count(usage.get("estimated_prompt_tokens"))


USAGE_SOURCE_LABELS = {"explore": "by explore", "compact": "for compaction"}


@dataclass
class Usage:
    """Token counts summed over model calls, as reported by the API (or estimated when it reports none)."""
    calls: int = 0
    by_source: dict = field(default_factory=dict)
    estimated: int = 0
    prompt_tokens: int = 0
    cached_tokens: int = 0
    completion_tokens: int = 0
    peak_prompt_tokens: int = 0

    def add(self, usage: dict, source: str = "main") -> None:
        self.calls += 1
        self.by_source[source] = self.by_source.get(source, 0) + 1
        prompt = prompt_size(usage)
        self.estimated += "prompt_tokens" not in usage
        details = usage.get("prompt_tokens_details")
        self.prompt_tokens += prompt
        self.cached_tokens += token_count(details.get("cached_tokens")) if isinstance(details, dict) else 0
        self.completion_tokens += token_count(usage.get("completion_tokens"))
        self.peak_prompt_tokens = max(self.peak_prompt_tokens, prompt)

    def merge(self, other: "Usage") -> None:
        self.calls += other.calls
        for source, count in other.by_source.items():
            self.by_source[source] = self.by_source.get(source, 0) + count
        self.estimated += other.estimated
        self.prompt_tokens += other.prompt_tokens
        self.cached_tokens += other.cached_tokens
        self.completion_tokens += other.completion_tokens
        self.peak_prompt_tokens = max(self.peak_prompt_tokens, other.peak_prompt_tokens)

    def summary(self, label: str = "[Usage]") -> str:
        calls = f"{self.calls} model call{'s' if self.calls != 1 else ''}"
        extra = [f"{count} {USAGE_SOURCE_LABELS.get(source, source)}"
                 for source, count in sorted(self.by_source.items()) if source != "main"]
        if extra:
            calls += f" ({', '.join(extra)})"
        prompt = f"prompt {'~' if self.estimated else ''}{self.prompt_tokens:,} tokens"
        if self.cached_tokens:
            prompt += f" ({self.cached_tokens:,} cached)"
        parts = [calls, prompt]
        if self.estimated < self.calls:
            parts.append(f"completion {self.completion_tokens:,}")
        parts.append(f"largest prompt {self.peak_prompt_tokens:,}")
        if self.estimated:
            parts.append(f"~ estimated for {self.estimated} call{'s' if self.estimated != 1 else ''} without API usage")
        return f"{label} " + " | ".join(parts)


# ==================== chippy/terminal.py ====================

def sanitize(text) -> str:
    """
    Escapes control characters (ANSI escapes, carriage returns, bidi overrides) so
    model output cannot redraw the terminal or spoof the approval prompt.
    """
    out = []
    for ch in str(text):
        if ch in "\n\t" or ch.isprintable():
            out.append(ch)
            continue
        code = ord(ch)
        if code <= 0xFF:
            out.append(f"\\x{code:02x}")
        elif code <= 0xFFFF:
            out.append(f"\\u{code:04x}")
        else:
            out.append(f"\\U{code:08x}")
    return "".join(out)


def clip(text: str, limit: int) -> str:
    return text if len(text) <= limit else text[:limit] + "..."


# ==================== chippy/approval.py ====================

def _diff_lines(old_text: str, new_text: str, label: str) -> list:
    return list(difflib.unified_diff(
        old_text.splitlines(), new_text.splitlines(),
        fromfile=f"a/{label}", tofile=f"b/{label}", lineterm="",
    ))


def _print_diff(diff: list, limit=None) -> bool:
    """Prints the diff, returning True if it was cut short."""
    shown = diff if limit is None else diff[:limit]
    for line in shown:
        print(sanitize(line))
    if len(shown) < len(diff):
        print(f"... [{len(diff) - len(shown)} more diff lines]")
        return True
    return False


def request_write_approval(target: Path, workspace: Path, operation: str, old_text: str,
                           new_text: str, warnings: list, old_is_binary: bool = False) -> bool:
    """Shows the full change as a diff and asks the human to approve it."""
    label = target.relative_to(workspace.resolve()).as_posix()
    diff = _diff_lines("" if old_is_binary else old_text, new_text, label)
    old_lines = "binary" if old_is_binary else str(len(old_text.splitlines()))

    print("\n" + "=" * 60)
    print("[HUMAN APPROVAL REQUIRED: FILE WRITE]")
    print(f"Target Path: {sanitize(target)}")
    print(f"Operation  : {sanitize(operation)}")
    print(f"Size       : {len(new_text.encode('utf-8'))} bytes")
    print(f"Lines      : {old_lines} -> {len(new_text.splitlines())}")
    for warning in warnings:
        print(f"!! WARNING : {warning}")
    if old_is_binary:
        print("!! WARNING : the existing file is binary and will be replaced; diff is against an empty file")
    print("-" * 60)
    truncated = _print_diff(diff, APPROVAL_DIFF_PREVIEW_LINES)
    print("=" * 60)

    prompt = "Allow write operation? [y/N" + ("/v = view full diff" if truncated else "") + "]: "
    while True:
        try:
            decision = input(prompt).strip().lower()
        except EOFError:
            return False
        if decision in ("y", "yes"):
            return True
        if decision == "v" and truncated:
            _print_diff(diff)
            continue
        return False


# ==================== chippy/sandbox.py ====================

# Never readable or writable by the agent: hooks under .git/ run code on commit,
# and .git/config can hold credentials in remote URLs.
PROTECTED_DIR_NAMES = frozenset({".git"})

# Reads need no human approval and their contents go straight to the API, so likely
# secrets are refused. Patterns without "/" match the file name, others the relative path.
SECRET_FILE_PATTERNS = (
    ".env", ".env.*", "*.pem", "*.key", "*.p12", "*.pfx",
    "id_rsa*", "id_dsa*", "id_ecdsa*", "id_ed25519*",
    ".netrc", ".npmrc", ".pypirc",
)
SECRET_FILE_EXCEPTIONS = (".env.example", ".env.sample", ".env.template")

# Files that cause code to run later. Writes are still allowed, but the approval prompt flags them.
RISKY_WRITE_PATTERNS = (
    (".envrc", "direnv executes this when you enter the directory"),
    ("makefile", "make targets run shell commands"),
    ("gnumakefile", "make targets run shell commands"),
    ("package.json", "npm scripts run shell commands, including install hooks"),
    ("setup.py", "runs when the package is built or installed"),
    ("pyproject.toml", "configures build backends and hooks"),
    ("conftest.py", "pytest imports and runs this automatically"),
    (".pre-commit-config.yaml", "pre-commit runs these hooks on every commit"),
    (".vscode/*", "editor tasks and settings can run commands"),
    (".idea/*", "IDE run configurations can run commands"),
    (".github/workflows/*", "CI runs these with repository secrets"),
    (".gitlab-ci.yml", "CI runs these with repository secrets"),
    ("*.sh", "shell script"),
)


def resolve_scoped_path(rel_or_abs_path: str, workspace: Path) -> Path:
    """
    Resolves target path to its canonical form and verifies it strictly resides
    within the target workspace. Raises PermissionError on any escape attempt.
    """
    base = workspace.resolve()
    target = (base / rel_or_abs_path).resolve()

    # The canonical target path must be base or a descendant of base
    if target != base and base not in target.parents:
        raise PermissionError(
            f"Security Violation: Path '{rel_or_abs_path}' resolves to '{target}', "
            f"which escapes the designated workspace '{base}'."
        )
    return target


def _relative(target: Path, workspace: Path) -> Path:
    return target.relative_to(workspace.resolve())


def _matches(rel: Path, pattern: str) -> bool:
    # Case-insensitive: macOS and Windows filesystems treat ".GIT" and ".git" as the same directory.
    pattern = pattern.lower()
    subject = rel.as_posix() if "/" in pattern else rel.name
    return fnmatch.fnmatchcase(subject.lower(), pattern)


def is_protected(target: Path, workspace: Path) -> bool:
    return any(part.lower() in PROTECTED_DIR_NAMES for part in _relative(target, workspace).parts)


def is_secret(target: Path, workspace: Path) -> bool:
    rel = _relative(target, workspace)
    if any(_matches(rel, pattern) for pattern in SECRET_FILE_EXCEPTIONS):
        return False
    return any(_matches(rel, pattern) for pattern in SECRET_FILE_PATTERNS)


def check_listable(path: str, workspace: Path) -> Path:
    target = resolve_scoped_path(path, workspace)
    if is_protected(target, workspace):
        raise PermissionError(f"Access to '{path}' is blocked: version-control internals are off limits.")
    return target


def check_readable(path: str, workspace: Path) -> Path:
    target = check_listable(path, workspace)
    if is_secret(target, workspace):
        raise PermissionError(f"Access to '{path}' is blocked: it looks like a secrets file.")
    return target


def check_writable(path: str, workspace: Path) -> Path:
    return check_listable(path, workspace)


def write_warnings(target: Path, workspace: Path) -> list:
    """Reasons a write to `target` deserves extra scrutiny from the human approver."""
    rel = _relative(target, workspace)
    warnings = [reason for pattern, reason in RISKY_WRITE_PATTERNS if _matches(rel, pattern)]
    if is_secret(target, workspace):
        warnings.append("looks like a secrets file")
    return warnings


# ==================== chippy/tools.py ====================

def _tool_errors(func):
    """Turns exceptions into tool results so a failing tool never ends the session."""
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except PermissionError as pe:
            return {"status": "denied", "message": str(pe)}
        except Exception as e:
            return {"status": "error", "message": f"{type(e).__name__}: {e}"}
    return wrapper


def _as_int(value, name: str) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        raise ValueError(f"'{name}' must be an integer, got {value!r}") from None


def _as_bool(value) -> bool:
    if isinstance(value, str):
        return value.strip().lower() in ("true", "1", "yes")
    return bool(value)


def _is_binary(path: Path) -> bool:
    with open(path, "rb") as f:
        return b"\x00" in f.read(BINARY_SNIFF_BYTES)


def _read_text(path: Path, strict: bool) -> tuple:
    """
    Returns (text, newline). Text always uses '\\n' line endings; `newline` is the
    file's original ending so writes can restore it.
    """
    raw = path.read_bytes()
    newline = "\r\n" if b"\r\n" in raw else "\n"
    text = raw.decode("utf-8", errors="strict" if strict else "replace")
    return text.replace("\r\n", "\n"), newline


def _default_file_mode() -> int:
    umask = os.umask(0)
    os.umask(umask)
    return 0o666 & ~umask


def _atomic_write(target: Path, text: str, newline: str) -> None:
    """Writes via a temp file + rename so an interrupted write never leaves a half-written file."""
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = stat.S_IMODE(target.stat().st_mode) if target.exists() else _default_file_mode()
    fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline=newline) as f:
            f.write(text)
        os.chmod(tmp, mode)
        os.replace(tmp, target)
    except BaseException:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass
        raise


def _iter_lines(f, max_chars: int):
    """Yields (line, clipped), capping each line at max_chars without loading over-long lines into memory."""
    while True:
        line = f.readline(max_chars)
        if not line:
            return
        clipped = False
        if len(line) >= max_chars and not line.endswith(("\n", "\r")):
            ending = ""
            rest = f.readline(max_chars)
            while rest:
                if rest.endswith(("\n", "\r")):
                    ending = "\n"
                    break
                rest = f.readline(max_chars)
            clipped = True
            line = f"{line}... [line clipped at {max_chars} chars]{ending}"
        yield line.replace("\r\n", "\n"), clipped


def _walk_files(root: Path):
    """Yields files under root (or root itself), sorted, skipping WALK_SKIP_DIRS. Symlinked dirs are not followed."""
    if not root.is_dir():
        yield root
        return
    for cur_root, dirs, names in os.walk(root):
        dirs[:] = sorted(d for d in dirs if d not in WALK_SKIP_DIRS)
        for name in sorted(names):
            yield Path(cur_root) / name


# ==========================================
# Tools
# ==========================================

@_tool_errors
def tool_list_directory(workspace: Path, directory_path: str = ".") -> dict:
    """Lists entries inside a specified directory relative to workspace root."""
    target = check_listable(directory_path or ".", workspace)
    if not target.exists():
        return {"status": "error", "message": f"Directory '{directory_path}' does not exist."}
    if not target.is_dir():
        return {"status": "error", "message": f"Path '{directory_path}' is not a directory."}

    children = sorted(target.iterdir())
    entries = []
    for entry in children[:LIST_MAX_ENTRIES]:
        item = {"name": entry.name}
        if entry.is_symlink():
            item["is_symlink"] = True
            try:
                resolve_scoped_path(str(entry), workspace)
            except PermissionError:
                # Don't stat it: that would leak metadata about files outside the workspace.
                item["outside_workspace"] = True
                entries.append(item)
                continue
        try:
            st = entry.stat()
        except OSError:
            item["error"] = "unreadable (broken symlink?)"
            entries.append(item)
            continue
        is_dir = stat.S_ISDIR(st.st_mode)
        item["is_dir"] = is_dir
        item["size_bytes"] = None if is_dir else st.st_size
        entries.append(item)

    result = {"status": "success", "entries": entries}
    if len(children) > LIST_MAX_ENTRIES:
        result["truncated"] = True
        result["note"] = f"Showing the first {LIST_MAX_ENTRIES} of {len(children)} entries."
    return result


@_tool_errors
def tool_read_file(workspace: Path, file_path: str, offset=1, limit=READ_MAX_LINES) -> dict:
    """Safely reads a window of lines from a text file within the workspace."""
    target = check_readable(file_path, workspace)
    if not target.exists():
        return {"status": "error", "message": f"File '{file_path}' does not exist."}
    if not target.is_file():
        return {"status": "error", "message": f"Path '{file_path}' is not a regular file."}
    offset = _as_int(offset, "offset")
    if offset < 1:
        return {"status": "error", "message": "'offset' must be 1 or greater."}
    limit = max(1, min(_as_int(limit, "limit"), READ_MAX_LINES))
    if _is_binary(target):
        return {"status": "error", "message": f"File '{file_path}' appears to be binary."}

    lines, chars, clipped_count, line_no, has_more = [], 0, 0, 0, False
    with open(target, "r", encoding="utf-8", errors="replace", newline="") as f:
        for line_no, (line, clipped) in enumerate(_iter_lines(f, READ_MAX_LINE_CHARS), start=1):
            if line_no < offset:
                continue
            if len(lines) >= limit or chars + len(line) > READ_MAX_CHARS:
                has_more = True
                break
            lines.append(line)
            chars += len(line)
            clipped_count += clipped

    if not lines and offset > 1:
        return {"status": "error", "message": f"'offset' {offset} is past the end of the file ({line_no} lines)."}

    end_line = offset + len(lines) - 1
    result = {
        "status": "success",
        "content": "".join(lines),
        "start_line": offset,
        "end_line": end_line,
        "has_more": has_more,
    }
    notes = []
    if has_more:
        result["next_offset"] = end_line + 1
        notes.append(f"Showing lines {offset}-{end_line}. Call read_file with offset={end_line + 1} to continue.")
    if clipped_count:
        notes.append(f"{clipped_count} over-long line(s) were clipped to {READ_MAX_LINE_CHARS} characters.")
    if not notes:
        notes.append("Full file content" if offset == 1 else "End of file")
    result["note"] = " ".join(notes)
    return result


@_tool_errors
def tool_search_files(workspace: Path, pattern: str, path: str = ".", glob: str = "",
                      ignore_case=False, context=0) -> dict:
    """
    Regex search over text files, returning 'path:line: text' hits so the model can read
    just those lines. With context, each hit is a block that also has the surrounding
    lines, marked grep-style as 'path-line- text'.
    """
    if not isinstance(pattern, str) or not pattern:
        return {"status": "error", "message": "'pattern' must be a non-empty string."}
    try:
        regex = re.compile(pattern, re.IGNORECASE if _as_bool(ignore_case) else 0)
    except re.error as e:
        return {"status": "error", "message": f"Invalid regular expression: {e}"}
    context = max(0, min(_as_int(context, "context"), SEARCH_MAX_CONTEXT_LINES))
    root = check_listable(path or ".", workspace)
    if not root.exists():
        return {"status": "error", "message": f"Path '{path}' does not exist."}

    base = workspace.resolve()
    matches, files_matched, files_scanned, stop_reason = [], 0, 0, ""
    for candidate in _walk_files(root):
        rel = candidate.relative_to(base).as_posix()
        if glob and not fnmatch.fnmatch(rel if "/" in glob else candidate.name, glob):
            continue
        try:
            # Resolves symlinks and refuses secrets, exactly like read_file.
            target = check_readable(rel, workspace)
        except PermissionError:
            continue
        if not target.is_file() or target.stat().st_size > SEARCH_MAX_FILE_BYTES or _is_binary(target):
            continue
        if files_scanned >= SEARCH_MAX_FILES:
            stop_reason = f"Stopped after scanning {SEARCH_MAX_FILES} files; narrow 'path' or 'glob'."
            break
        files_scanned += 1
        found = False
        with open(target, "r", encoding="utf-8", errors="replace", newline="") as f:
            lines = [line.rstrip("\n") for line, _ in _iter_lines(f, READ_MAX_LINE_CHARS)]
        for index, line in enumerate(lines):
            if not regex.search(line):
                continue
            if len(matches) >= SEARCH_MAX_MATCHES:
                stop_reason = f"Showing the first {SEARCH_MAX_MATCHES} matches; narrow the pattern, 'path' or 'glob'."
                break
            found = True
            block = []
            for i in range(max(0, index - context), min(len(lines), index + context + 1)):
                mark = ":" if i == index else "-"
                block.append(f"{rel}{mark}{i + 1}{mark} {clip(lines[i].rstrip(), SEARCH_MAX_LINE_CHARS)}")
            matches.append("\n".join(block))
        files_matched += found
        if stop_reason:
            break

    result = {"status": "success", "matches": matches, "files_matched": files_matched}
    if stop_reason:
        result["truncated"] = True
        result["note"] = stop_reason
    elif not matches:
        result["note"] = f"No matches in {files_scanned} file(s) searched."
    return result


@_tool_errors
def tool_write_file(workspace: Path, file_path: str, content: str) -> dict:
    """Prompts human approval (with a diff) before creating or overwriting a file."""
    target = check_writable(file_path, workspace)
    if target.is_dir():
        return {"status": "error", "message": f"Path '{file_path}' is a directory."}
    if not isinstance(content, str):
        return {"status": "error", "message": "'content' must be a string."}

    exists = target.exists()
    old_text, newline, old_is_binary = "", "\n", False
    if exists:
        old_is_binary = _is_binary(target)
        if not old_is_binary:
            old_text, newline = _read_text(target, strict=False)
    new_text = content.replace("\r\n", "\n")
    if exists and not old_is_binary and new_text == old_text:
        return {"status": "success", "message": f"No changes: '{file_path}' already has this content."}

    approved = request_write_approval(
        target, workspace, "Overwrite" if exists else "Create new file",
        old_text, new_text, write_warnings(target, workspace), old_is_binary=old_is_binary,
    )
    if not approved:
        return {"status": "denied", "message": "File write rejected by human supervisor."}

    _atomic_write(target, new_text, newline)
    return {"status": "success", "message": f"Wrote {len(new_text.splitlines())} lines to {file_path}."}


@_tool_errors
def tool_edit_file(workspace: Path, file_path: str, old_string: str, new_string: str, replace_all=False) -> dict:
    """Replaces an exact, unique snippet in an existing file, after human approval."""
    # Readable check too: match/no-match errors would otherwise reveal the contents of secret files.
    target = check_readable(file_path, workspace)
    check_writable(file_path, workspace)
    if not target.is_file():
        return {"status": "error", "message": f"File '{file_path}' does not exist. Use write_file to create it."}
    if not isinstance(old_string, str) or not isinstance(new_string, str):
        return {"status": "error", "message": "'old_string' and 'new_string' must be strings."}
    if not old_string:
        return {"status": "error", "message": "'old_string' must not be empty. Use write_file to create or replace whole files."}
    if old_string == new_string:
        return {"status": "error", "message": "'old_string' and 'new_string' are identical."}
    if _is_binary(target):
        return {"status": "error", "message": f"File '{file_path}' appears to be binary."}
    try:
        text, newline = _read_text(target, strict=True)
    except UnicodeDecodeError:
        return {"status": "error", "message": f"File '{file_path}' is not valid UTF-8; editing it could corrupt it."}

    old = old_string.replace("\r\n", "\n")
    new = new_string.replace("\r\n", "\n")
    count = text.count(old)
    if count == 0:
        return {"status": "error", "message": "'old_string' was not found. Read the file again and copy the text exactly, including whitespace."}
    replace_all = _as_bool(replace_all)
    if count > 1 and not replace_all:
        return {"status": "error", "message": f"'old_string' appears {count} times. Include more surrounding context to make it unique, or set replace_all=true."}

    replaced = count if replace_all else 1
    new_text = text.replace(old, new, -1 if replace_all else 1)
    approved = request_write_approval(
        target, workspace, f"Edit ({replaced} replacement{'s' if replaced > 1 else ''})",
        text, new_text, write_warnings(target, workspace),
    )
    if not approved:
        return {"status": "denied", "message": "File edit rejected by human supervisor."}

    _atomic_write(target, new_text, newline)
    return {"status": "success", "message": f"Replaced {replaced} occurrence(s) in {file_path}."}


# ==========================================
# Registry: the single source of truth for tool names, schemas and handlers
# ==========================================

_REGISTRY = (
    (tool_list_directory, {
        "name": "list_directory",
        "description": f"List files and subdirectories within a given relative folder path (up to {LIST_MAX_ENTRIES} entries).",
        "parameters": {
            "type": "object",
            "properties": {
                "directory_path": {
                    "type": "string",
                    "description": "Relative directory path. Use '.' or '' for root.",
                },
            },
            "required": ["directory_path"],
        },
    }),
    (tool_read_file, {
        "name": "read_file",
        "description": (
            f"Read a UTF-8 text file, at most {READ_MAX_LINES} lines per call. "
            "Read only the lines you need (offset/limit, e.g. around a search_files hit) instead of whole files. "
            "If the result has has_more=true, call again with offset=next_offset to read the rest. "
            "Always read the whole file before rewriting it with write_file."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Relative path of the file to inspect."},
                "offset": {"type": "integer", "description": "1-based line number to start from. Defaults to 1."},
                "limit": {"type": "integer", "description": f"Maximum lines to return (1-{READ_MAX_LINES}). Defaults to {READ_MAX_LINES}."},
            },
            "required": ["file_path"],
        },
    }),
    (tool_search_files, {
        "name": "search_files",
        "description": (
            f"Search text files for a regular expression (Python syntax). Returns up to {SEARCH_MAX_MATCHES} "
            "'path:line: text' matches. Use it to find where something is defined or used, then read_file "
            "just those lines with offset/limit."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "pattern": {"type": "string", "description": "Regular expression to search for."},
                "path": {"type": "string", "description": "Relative file or directory to search. Defaults to the workspace root."},
                "glob": {"type": "string", "description": "Only search files matching this pattern, e.g. '*.py' or 'src/*.ts'."},
                "ignore_case": {"type": "boolean", "description": "Case-insensitive search."},
                "context": {
                    "type": "integer",
                    "description": f"Lines of context to show around each match (0-{SEARCH_MAX_CONTEXT_LINES}). Defaults to 0.",
                },
            },
            "required": ["pattern"],
        },
    }),
    (tool_write_file, {
        "name": "write_file",
        "description": (
            "Create a new file, or replace an existing file's entire content. Requires human approval. "
            "Prefer edit_file for changes to existing files."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Relative path of the target file to create or replace."},
                "content": {"type": "string", "description": "The exact full text content to write."},
            },
            "required": ["file_path", "content"],
        },
    }),
    (tool_edit_file, {
        "name": "edit_file",
        "description": (
            "Replace an exact snippet of an existing file with new text. Requires human approval. "
            "old_string must match the file exactly (including whitespace) and be unique unless replace_all is true."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Relative path of the file to edit."},
                "old_string": {"type": "string", "description": "Exact text to replace."},
                "new_string": {"type": "string", "description": "Replacement text."},
                "replace_all": {"type": "boolean", "description": "Replace every occurrence instead of requiring a unique match."},
            },
            "required": ["file_path", "old_string", "new_string"],
        },
    }),
)

TOOL_HANDLERS = {schema["name"]: handler for handler, schema in _REGISTRY}
TOOLS = [{"type": "function", "function": schema} for _, schema in _REGISTRY]

# The explore sub-agent gets these only: it gathers context and never changes files.
READ_ONLY_TOOL_NAMES = ("list_directory", "read_file", "search_files")
READ_ONLY_TOOLS = [tool for tool in TOOLS if tool["function"]["name"] in READ_ONLY_TOOL_NAMES]

# Run by the agent loop rather than dispatch_tool, since it starts a sub-agent (see explore.py).
EXPLORE_TOOL_NAME = "explore"
EXPLORE_TOOL = {"type": "function", "function": {
    "name": EXPLORE_TOOL_NAME,
    "description": (
        "Hand a context-gathering task to a read-only sub-agent with a fresh context. It searches and reads "
        "the workspace and returns a compact brief: the relevant file:line ranges with their exact text "
        "(copied from the files by the harness), applicable AGENTS.md rules, assumptions, and the user's "
        "answers to any blocking questions. "
        "Use it before multi-file changes or when you don't know where the relevant code is; "
        "skip it for small, local tasks."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "task": {
                "type": "string",
                "description": "What you are about to do and what you need to know to do it.",
            },
        },
        "required": ["task"],
    },
}}
AGENT_TOOLS = TOOLS + [EXPLORE_TOOL]


def parse_tool_arguments(raw_arguments) -> tuple:
    """Returns (arguments dict, None) or (None, error result)."""
    if isinstance(raw_arguments, dict):
        args = raw_arguments
    else:
        try:
            args = json.loads(raw_arguments) if raw_arguments else {}
        except (TypeError, ValueError) as e:
            return None, {"status": "error", "message": f"Arguments are not valid JSON ({e}). Retry with a JSON object."}
    if not isinstance(args, dict):
        return None, {"status": "error", "message": "Arguments must be a JSON object."}
    return args, None


def tool_result_message(call: dict, result: dict) -> dict:
    return {
        "role": "tool",
        "tool_call_id": call.get("id"),
        "name": (call.get("function") or {}).get("name") or "",
        "content": json.dumps(result),
    }


def dispatch_tool(name: str, raw_arguments, workspace: Path, allowed=None) -> dict:
    """
    Runs one model tool call, limited to the `allowed` tool names if given.
    Bad names or arguments become error results the model can correct.
    """
    available = tuple(TOOL_HANDLERS) if allowed is None else tuple(allowed)
    handler = TOOL_HANDLERS.get(name) if name in available else None
    if handler is None:
        return {"status": "error", "message": f"Unknown tool: {name!r}. Available tools: {', '.join(available)}."}

    args, error = parse_tool_arguments(raw_arguments)
    if error:
        return error

    try:
        inspect.signature(handler).bind(workspace, **args)
    except TypeError as e:
        return {"status": "error", "message": f"Invalid arguments for {name}: {e}"}
    return handler(workspace, **args)


UNCHANGED_READ_RESULT = {
    "status": "success",
    "unchanged": True,
    "message": "You already read these lines earlier in this request and the file has not changed since; use that result.",
}


def _read_key(raw_arguments, workspace: Path):
    """Identifies a read_file call's output: the file, the window and the file's current version."""
    args, error = parse_tool_arguments(raw_arguments)
    if error or not isinstance(args.get("file_path"), str):
        return None
    try:
        target = check_readable(args["file_path"], workspace)
        st = target.stat()
        offset = _as_int(args.get("offset", 1), "offset")
        limit = _as_int(args.get("limit", READ_MAX_LINES), "limit")
    except (OSError, ValueError):  # PermissionError is an OSError
        return None
    return str(target), offset, limit, st.st_mtime_ns, st.st_size


class ReadTracker:
    """
    Dispatches tool calls, answering a repeated read_file of the same unchanged lines
    with a short note instead of the content again. Clear it whenever earlier tool
    output may have left the conversation (elision or compaction).
    """

    def __init__(self):
        self._seen = set()

    def clear(self) -> None:
        self._seen.clear()

    def dispatch(self, name: str, raw_arguments, workspace: Path, allowed=None) -> dict:
        key = _read_key(raw_arguments, workspace) if name == "read_file" else None
        if key is not None and key in self._seen:
            return dict(UNCHANGED_READ_RESULT)
        result = dispatch_tool(name, raw_arguments, workspace, allowed)
        if key is not None and result.get("status") == "success":
            self._seen.add(key)
        return result


# ==================== chippy/compact.py ====================

SUMMARY_PROMPT = """You compress the conversation of an engineering agent so it can continue the work with a much smaller context.
Write a concise plain-text summary with these sections:
1. User requests and preferences: what the user asked for, in their own words where it matters.
2. Decisions and answers: choices made, and answers the user gave to questions.
3. Work done: files created or changed, and what changed in each.
4. Key findings: file:line locations, facts about the code, and AGENTS.md rules that apply.
5. Current state and next steps: what was in progress and what remains.
Do not copy file contents except very short snippets that are essential; files can be re-read."""

COMPACTED_PREFIX = ("[Context compacted] The earlier conversation was replaced by this summary to save context. "
                    "Re-read files with the tools when you need their exact contents.\n\n")
COMPACTED_ACK = "Understood. I'll continue from this summary."


def _last_user_index(messages: list):
    return max((i for i, m in enumerate(messages) if m.get("role") == "user"), default=None)


def tail_start(messages: list, keep_steps: int) -> int:
    """
    Index where the verbatim tail begins: the last `keep_steps` model steps of the current
    request, or the request's own user message if it has no more steps than that.
    A tail never starts with a tool result, so cutting there keeps every tool call answered.
    """
    if keep_steps <= 0:
        return len(messages)
    last_user = _last_user_index(messages)
    first = 0 if last_user is None else last_user + 1
    steps = [i for i in range(first, len(messages)) if messages[i].get("role") == "assistant"]
    if len(steps) > keep_steps:
        return steps[-keep_steps]
    return len(messages) if last_user is None else last_user


def _stub_arguments(raw):
    """Tool-call arguments with long string values replaced by a size note. Returns None if nothing changed."""
    try:
        args = json.loads(raw) if isinstance(raw, str) else raw
    except ValueError:
        return json.dumps({"elided": f"{len(raw):,} chars of malformed arguments"}) if len(raw) >= ELIDE_ARG_MIN_CHARS else None
    if not isinstance(args, dict):
        return None
    stubbed = {key: f"[{len(value):,} chars elided]" if isinstance(value, str) and len(value) >= ELIDE_ARG_MIN_CHARS else value
               for key, value in args.items()}
    return json.dumps(stubbed) if stubbed != args else None


def elide_tool_output(messages: list, end: int, keep_briefs: bool = True) -> int:
    """
    Stubs bulky tool results and large tool-call arguments in messages[:end].
    Explore briefs are kept unless keep_briefs is False. Returns the number of stubs made.
    """
    calls, elided = {}, 0
    for index in range(min(end, len(messages))):
        message = messages[index]
        if message.get("tool_calls"):
            new_calls = []
            for call in message["tool_calls"]:
                function = call.get("function") or {}
                calls[call.get("id")] = function
                stubbed = _stub_arguments(function.get("arguments"))
                if stubbed is not None:
                    call = {**call, "function": {**function, "arguments": stubbed}}
                    elided += 1
                new_calls.append(call)
            messages[index] = {**message, "tool_calls": new_calls}
        if message.get("role") != "tool" or (keep_briefs and message.get("name") == EXPLORE_TOOL_NAME):
            continue
        if len(message.get("content") or "") < ELIDE_MIN_CHARS:
            continue
        function = calls.get(message.get("tool_call_id"), {})
        signature = f"{function.get('name') or message.get('name')}({clip(str(function.get('arguments') or ''), 200)})"
        messages[index] = {**message, "content": json.dumps({
            "status": "elided",
            "message": f"Output of {signature} was removed to save context. Call the tool again if you still need it.",
        })}
        elided += 1
    return elided


def elide_stale_tool_results(messages: list) -> int:
    """
    Run when a new request starts: elides tool output from before the most recent request.
    Doing it only at this boundary keeps the API's prompt cache valid within a request.
    """
    last_user = _last_user_index(messages)
    return 0 if last_user is None else elide_tool_output(messages, last_user)


def render_transcript(messages: list, max_chars: int) -> str:
    """Plain-text transcript for the summarizer, with long parts clipped and the middle dropped if needed."""
    parts = []
    for message in messages:
        role = message.get("role")
        if role == "user":
            parts.append(f"USER: {message.get('content') or ''}")
        elif role == "assistant":
            if message.get("content"):
                parts.append(f"ASSISTANT: {message['content']}")
            for call in message.get("tool_calls") or []:
                function = call.get("function") or {}
                parts.append(f"TOOL CALL: {function.get('name')}"
                             f"({clip(str(function.get('arguments') or ''), COMPACT_TRANSCRIPT_ARG_CHARS)})")
        elif role == "tool":
            parts.append(f"TOOL RESULT ({message.get('name')}): "
                         f"{clip(str(message.get('content') or ''), COMPACT_TRANSCRIPT_RESULT_CHARS)}")
    text = "\n\n".join(parts)
    if len(text) <= max_chars:
        return text
    head = max_chars // 4
    return text[:head] + "\n\n[... middle of the conversation omitted ...]\n\n" + text[-(max_chars - head):]


def _summarize(messages: list, settings: Settings, usage: Usage, instructions: str) -> str:
    max_chars = int(settings.context_limit * CHARS_PER_TOKEN * COMPACT_SUMMARY_INPUT_RATIO)
    system = SUMMARY_PROMPT + (f"\n\nThe user asked the summary to focus on: {instructions}" if instructions else "")
    for _ in range(3):
        request = [
            {"role": "system", "content": system},
            {"role": "user", "content": render_transcript(messages, max_chars)},
        ]
        try:
            response, call_usage = call_llm_api(request, [], settings, source="compact")
        except ContextLengthError:
            max_chars //= 2
            continue
        usage.add(call_usage, "compact")
        summary = (response.get("content") or "").strip()
        if not summary:
            raise LLMError("The model returned an empty summary.")
        return summary
    raise LLMError("The conversation is too large to summarize even after shortening it.")


def compact_history(messages: list, settings: Settings, usage: Usage, keep_steps: int,
                    mid_request: bool, instructions: str = "") -> bool:
    """
    Replaces everything between the system prompt and the verbatim tail with a summary.
    If the current request's message gets summarized mid-request, it is repeated
    verbatim so the model still has the user's exact instructions. Returns False if
    there was nothing to compact. Raises LLMError if summarizing fails.
    """
    start = tail_start(messages, keep_steps)
    if start <= 1:
        return False
    head, tail = messages[1:start], messages[start:]
    summary = COMPACTED_PREFIX + _summarize(head, settings, usage, instructions)
    last_user = _last_user_index(messages)
    if mid_request and last_user is not None and 0 < last_user < start:
        request = messages[last_user].get("content") or ""
        # An earlier summary already carries the request, and the new summary is made from it.
        if not request.startswith(COMPACTED_PREFIX):
            summary += f"\n\nThe user's current request, verbatim:\n{request}"

    new = [messages[0], {"role": "user", "content": summary}]
    if (tail and tail[0].get("role") == "user") or (not tail and not mid_request):
        new.append({"role": "assistant", "content": COMPACTED_ACK})
    messages[:] = new + tail
    return True


class ContextMeter:
    """
    Tracks the conversation's size in tokens: the prompt size of the last model call
    plus an estimate for what was added since. Reset it after history is rewritten.
    """

    def __init__(self):
        self._last = None  # (number of messages sent, prompt tokens)

    def record(self, sent_messages: int, usage: dict) -> None:
        tokens = prompt_size(usage)
        self._last = (sent_messages, tokens) if tokens else None

    def reset(self) -> None:
        self._last = None

    def estimate(self, messages: list, tools: list) -> int:
        if self._last and self._last[0] <= len(messages):
            sent, tokens = self._last
            return tokens + estimate_tokens(messages[sent:])
        return estimate_tokens(messages) + estimate_tokens(tools)


def ensure_room(messages: list, settings: Settings, usage: Usage, meter: ContextMeter, tools: list) -> bool:
    """
    Auto-compaction, run before each model call. Near the context limit, older tool
    output is elided first; if that isn't enough, earlier conversation is summarized.
    Returns True if the history changed.
    """
    limit = settings.context_limit
    before = meter.estimate(messages, tools)
    if before < limit * COMPACT_TRIGGER_RATIO:
        return False
    elided = elide_tool_output(messages, tail_start(messages, COMPACT_KEEP_STEPS), keep_briefs=False)
    meter.reset()
    summarized = False
    if meter.estimate(messages, tools) > limit * COMPACT_TARGET_RATIO:
        print("[Context] Near the context limit; summarizing earlier conversation...")
        try:
            summarized = compact_history(messages, settings, usage, COMPACT_KEEP_STEPS, mid_request=True)
        except LLMError as e:
            # Not fatal: the request goes ahead, and an overflow is still recovered from.
            print(f"[Context] Summarizing failed ({clip(str(e), 200)}); continuing without it.")
    after = meter.estimate(messages, tools)
    if elided or summarized:
        print(f"[Context] Auto-compacted: ~{before:,} -> ~{after:,} tokens (limit {limit:,}).")
    return bool(elided or summarized)


def recover_from_overflow(messages: list, settings: Settings, usage: Usage, meter: ContextMeter) -> bool:
    """
    After the API rejected a request as too long: elides all tool output and summarizes
    everything but the system prompt. Returns True if the history changed.
    """
    elided = elide_tool_output(messages, len(messages), keep_briefs=False)
    meter.reset()
    return bool(compact_history(messages, settings, usage, keep_steps=0, mid_request=True) or elided)


# ==================== chippy/context.py ====================

_HEADING = re.compile(r"^#{1,6}\s+\S")
_FENCE = re.compile(r"^\s*(```|~~~)")


def outline_markdown(text: str) -> list:
    """Headings with the line ranges they cover, e.g. 'L20-30: ## Testing'. Ignores '#' lines inside code fences."""
    lines = text.splitlines()
    starts, in_fence = [], False
    for number, line in enumerate(lines, start=1):
        if _FENCE.match(line):
            in_fence = not in_fence
        elif not in_fence and _HEADING.match(line):
            starts.append((number, line.strip()))
    if not starts:
        return []
    sections = []
    if starts[0][0] > 1 and any(line.strip() for line in lines[:starts[0][0] - 1]):
        sections.append(f"L1-{starts[0][0] - 1}: (text before the first heading)")
    for index, (start, heading) in enumerate(starts):
        end = starts[index + 1][0] - 1 if index + 1 < len(starts) else len(lines)
        sections.append(f"L{start}-{end}: {heading}")
    return sections


def load_agents_md(workspace: Path) -> tuple:
    """
    Returns (status for the banner, rules for the prompt). Short files are sent verbatim;
    long ones as an outline the model reads from on demand, so they don't fill every request.
    """
    # Goes through the sandbox: a symlinked AGENTS.md must not pull files from outside the workspace.
    try:
        path = check_readable("AGENTS.md", workspace)
    except PermissionError as e:
        return f"Ignored ({e})", "None provided."
    if not path.is_file():
        return "None", "None provided."
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return f"Unreadable ({e})", f"Error reading AGENTS.md: {e}"
    if len(text) <= AGENTS_MD_INLINE_CHARS:
        return "Detected", text

    sections = outline_markdown(text)
    if sections:
        return f"Detected ({len(text):,} chars, sent as an outline of {len(sections)} sections)", {
            "note": ("AGENTS.md is long, so only its outline is shown. Before acting, read the sections "
                     "relevant to your task with read_file('AGENTS.md', offset, limit)."),
            "sections": sections,
        }
    head = text[:AGENTS_MD_INLINE_CHARS]
    next_line = head.count("\n") + 1
    return (f"Detected ({len(text):,} chars, truncated)",
            head + f"\n... [AGENTS.md truncated; read the rest with read_file('AGENTS.md', offset={next_line})]")


def build_inventory(workspace: Path) -> list:
    """Sorted file map (depth-limited, capped) so the prompt is identical across runs."""
    base = workspace.resolve()
    files = []
    for cur_root, dirs, names in os.walk(base):
        rel = Path(cur_root).relative_to(base)
        if len(rel.parts) < INVENTORY_MAX_DEPTH:
            dirs[:] = sorted(d for d in dirs if d not in WALK_SKIP_DIRS)
        else:
            dirs[:] = []
        for name in sorted(names):
            files.append((rel / name).as_posix())
            if len(files) > INVENTORY_MAX_FILES:
                return files[:INVENTORY_MAX_FILES] + ["... [truncated]"]
    return files


def _render_prompt(intro: str, workspace: Path, agents_rules, tool_names, constraints: list) -> str:
    payload = {
        "agent_environment": {
            "os": platform.system(),
            "working_directory": str(workspace.resolve()),
            "isolation_mode": "No shell access; file tools are confined to the workspace",
        },
        "workspace_inventory": {
            "root_folder": workspace.name,
            "visible_files": build_inventory(workspace),
        },
        "agents_md_rules": agents_rules,
        "operating_constraints": [
            "You CANNOT execute terminal or shell commands (no bash, no powershell).",
            f"You only have access to these tools: {', '.join(tool_names)}.",
            "All paths must be relative to the scoped workspace.",
            "Any path referencing parent directories outside the workspace will trigger a hard security denial.",
            ".git/ and likely secrets files (.env, private keys) are off limits.",
            f"read_file returns at most {READ_MAX_LINES} lines per call; page through longer files with 'offset'.",
            "Locate code with search_files, then read only the lines you need with read_file offset/limit.",
            *constraints,
            "Follow all conventions defined in 'agents_md_rules'.",
        ],
    }
    return (
        intro + "\n"
        "Here is your initialization context payload:\n\n"
        "```json\n"
        + json.dumps(payload, indent=2) +
        "\n```"
    )


EXPLORE_GUIDANCE = {
    "auto": [
        "Before multi-file changes, or when you don't know where the relevant code is, call explore: "
        "it gathers context in a separate conversation and returns a compact brief. "
        "For small, local tasks use search_files and read_file directly.",
    ],
    "always": [
        "Every request starts with an explore call: describe the task and what you need to know in 'task'. "
        "Call explore again later only if the brief turns out to be missing something.",
    ],
    "never": [],
}
EXPLORE_SNIPPET_GUIDANCE = (
    "Snippets in an explore brief are copied from the files by the harness, so they are exact and can serve "
    "as edit_file old_string; if an edit fails, the file changed since, so re-read the lines."
)


def build_system_context(workspace: Path, explore_mode: str = "auto") -> tuple:
    """Returns (system prompt for the main agent, AGENTS.md status)."""
    agents_status, agents_rules = load_agents_md(workspace)
    explore_lines = EXPLORE_GUIDANCE[explore_mode] + ([EXPLORE_SNIPPET_GUIDANCE] if explore_mode != "never" else [])
    tool_names = [*TOOL_HANDLERS] + ([EXPLORE_TOOL_NAME] if explore_mode != "never" else [])
    prompt = _render_prompt(
        "You are an engineering assistant working in a sandboxed directory environment.",
        workspace, agents_rules, tool_names,
        [
            *explore_lines,
            "Read a whole file before rewriting it with write_file. "
            "Prefer edit_file for changes to existing files; use write_file to create files or replace them entirely.",
            "Every write is shown to a human as a diff and may be rejected.",
            "Old tool output may be elided, and the conversation may be replaced by a summary, to save context; "
            "call a tool again if you need its output.",
        ],
    )
    return prompt, agents_status


EXPLORE_BRIEF_FORMAT = """{
  "summary": "one or two sentences: what the task touches and how",
  "relevant": [{"file": "path", "lines": "40-62", "why": "..."}],
  "rules": ["AGENTS.md L20-30: the rule, paraphrased"],
  "assumptions": ["things you deduced but did not confirm"],
  "open_questions": ["only questions that block the task and cannot be answered from the code"]
}"""


def build_explorer_prompt(workspace: Path) -> str:
    """System prompt for the read-only explore sub-agent."""
    _, agents_rules = load_agents_md(workspace)
    return _render_prompt(
        "You are a read-only context scout. Another agent will carry out the task you are given; "
        "your job is to find exactly the context it needs, so it doesn't have to read whole files.",
        workspace, agents_rules, READ_ONLY_TOOL_NAMES,
        [
            "You cannot change files. Search first, then read narrow line ranges; avoid reading whole files.",
            "Collect the AGENTS.md rules that apply to the task (read the relevant sections if only an outline is shown).",
            "Resolve ambiguity by reading the code where you can. Ask open_questions only when the answer "
            "changes what should be done and the code cannot tell you; the user will be asked them.",
            "Don't copy code into the brief: give exact 'lines' ranges and the harness attaches the text of each. "
            "Make each range cover exactly what the task needs (e.g. the whole function to change).",
            "Keep the brief compact: include only what the task needs, not everything you read.",
            "When done, reply with ONLY a JSON object in this format (no prose, no code fence):\n"
            + EXPLORE_BRIEF_FORMAT,
        ],
    )


# ==================== chippy/explore.py ====================

FINAL_STEP_PROMPT = "Stop exploring now and reply with the JSON brief, based on what you found so far."
SKIPPED_ANSWER = ("The user skipped these questions. Decide using your best judgement and state your "
                  "assumptions, or ask the user in your reply.")
_LINE_RANGE = re.compile(r"\s*L?(\d+)\s*(?:-\s*L?(\d+))?\s*")


class ExploreInterrupted(KeyboardInterrupt):
    """Ctrl-C during explore. `result` lists what the explorer had looked at, for the caller's history."""

    def __init__(self, result: dict):
        super().__init__()
        self.result = result


def parse_brief(text: str):
    """The brief as a dict, or None if the reply is not a JSON object (an optional code fence is allowed)."""
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1].rsplit("```", 1)[0]
    try:
        brief = json.loads(text)
    except ValueError:
        return None
    return brief if isinstance(brief, dict) else None


def attach_snippets(brief: dict, workspace: Path) -> None:
    """
    Fills each 'relevant' entry's snippet with the exact text of its line range, read
    from disk by the harness, so snippets are correct by construction and the explorer
    never spends tokens copying code.
    """
    relevant = brief.get("relevant")
    if not isinstance(relevant, list):
        return
    for entry in relevant:
        if not isinstance(entry, dict):
            continue
        entry.pop("snippet", None)
        match = _LINE_RANGE.fullmatch(str(entry.get("lines", "")))
        start = int(match[1]) if match else 0
        end = int(match[2] or match[1]) if match else 0
        if not isinstance(entry.get("file"), str) or start < 1 or end < start:
            entry["snippet_error"] = "No snippet: 'file' or the 'start-end' line range is missing or invalid."
            continue
        result = tool_read_file(workspace, entry["file"], offset=start, limit=min(end - start + 1, EXPLORE_SNIPPET_MAX_LINES))
        if result.get("status") != "success":
            entry["snippet_error"] = f"No snippet: {result.get('message')}"
            continue
        entry["snippet"] = result["content"]
        if result["end_line"] < end:
            entry["snippet_note"] = f"Only lines {start}-{result['end_line']} are included; read the rest with read_file."


def _cap_read(raw_arguments):
    """The explorer's read_file calls are capped at EXPLORE_READ_MAX_LINES, so one read can't fill its context."""
    args, error = parse_tool_arguments(raw_arguments)
    if error:
        return raw_arguments
    try:
        limit = int(args.get("limit", EXPLORE_READ_MAX_LINES))
    except (TypeError, ValueError):
        return raw_arguments
    return {**args, "limit": max(1, min(limit, EXPLORE_READ_MAX_LINES))}


def _ask_open_questions(questions: list):
    """Puts the explorer's blocking questions to the user. Returns their answer, or None if skipped."""
    print("\n[Explore] Questions before the agent continues:")
    for number, question in enumerate(questions, start=1):
        print(f"  {number}. {sanitize(clip(str(question), 500))}")
    try:
        answer = input("Answer (Enter to let the agent decide) > ").strip()
    except EOFError:
        return None
    return answer or None


def _finish(reply: str, steps: int, workspace: Path) -> dict:
    print(f"[Explore] Done in {steps} step{'s' if steps != 1 else ''}.")
    brief = parse_brief(reply)
    if brief is None:
        return {"status": "success", "steps": steps, "brief": reply or "(the explorer returned nothing)"}
    attach_snippets(brief, workspace)
    questions = brief.get("open_questions")
    questions = [q for q in questions if q] if isinstance(questions, list) else []
    if questions:
        brief["user_answers"] = _ask_open_questions(questions) or SKIPPED_ANSWER
    return {"status": "success", "steps": steps, "brief": brief}


def run_explore(raw_arguments, workspace: Path, settings: Settings, usage: Usage) -> dict:
    """
    Runs the explore tool: a read-only sub-agent with its own conversation and step budget.
    Only its brief reaches the caller's context; the files it read do not. It is told to
    report early if its own context reaches EXPLORE_CONTEXT_RATIO of the limit.
    """
    args, error = parse_tool_arguments(raw_arguments)
    if error:
        return error
    task = args.get("task")
    if not isinstance(task, str) or not task.strip():
        return {"status": "error", "message": "'task' must be a non-empty string."}

    sub_settings = dataclasses.replace(settings, model=settings.explore_model or settings.model)
    budget = settings.context_limit * EXPLORE_CONTEXT_RATIO
    messages = [
        {"role": "system", "content": build_explorer_prompt(workspace)},
        {"role": "user", "content": task},
    ]
    reads, explored = ReadTracker(), []
    print(f"[Explore] Using {sanitize(sub_settings.model)}")
    try:
        for step in range(1, settings.explore_max_steps + 2):
            final = step > settings.explore_max_steps or estimate_tokens(messages) > budget
            if final:
                messages.append({"role": "user", "content": FINAL_STEP_PROMPT})
            response, call_usage = call_llm_api(messages, READ_ONLY_TOOLS, sub_settings,
                                                tool_choice="none" if final else "auto", source="explore")
            usage.add(call_usage, "explore")
            messages.append(response)

            tool_calls = response.get("tool_calls") or []
            if final or not tool_calls:
                return _finish(response.get("content") or "", step, workspace)
            for call in tool_calls:
                function = call.get("function") or {}
                name = function.get("name") or ""
                raw_args = _cap_read(function.get("arguments")) if name == "read_file" else function.get("arguments")
                signature = f"{name}({clip(str(function.get('arguments')), 120)})"
                print(f"  [explore] {sanitize(signature)}")
                result = reads.dispatch(name, raw_args, workspace, allowed=READ_ONLY_TOOL_NAMES)
                explored.append(signature)
                messages.append(tool_result_message(call, result))
    except LLMError as e:
        # Returned rather than raised: the caller's tool call still needs a result.
        return {"status": "error", "message": f"The explore sub-agent failed: {e}. Gather context directly instead."}
    except KeyboardInterrupt:
        raise ExploreInterrupted({
            "status": "cancelled",
            "message": "The user interrupted explore before it finished. It had looked at these, "
                       "so you know where to start if you continue:",
            "explored": explored,
        }) from None
    raise AssertionError("unreachable")


# ==================== chippy/agent.py ====================

CANCELLED_RESULT = {"status": "cancelled", "message": "Not run: the user interrupted this turn."}
COMMANDS_HELP = """Commands:
  /compact [focus]  Summarize the conversation so far to free context (optionally say what to keep)
  /usage            Token usage for this session and the current context size
  /help             Show this help
  exit, quit        Leave"""


def agent_tools(settings: Settings) -> list:
    return TOOLS if settings.explore_mode == "never" else AGENT_TOOLS


def _call_model(messages: list, tools: list, settings: Settings, usage: Usage, meter: ContextMeter,
                tool_choice, reads: ReadTracker) -> dict:
    """One model call. If the API rejects the prompt as too long, compacts everything and retries once."""
    try:
        response, call_usage = call_llm_api(messages, tools, settings, tool_choice)
    except ContextLengthError:
        print("[Context] The request exceeded the model's context window; compacting and retrying.")
        if not recover_from_overflow(messages, settings, usage, meter):
            raise
        reads.clear()
        response, call_usage = call_llm_api(messages, tools, settings, tool_choice)
    meter.record(len(messages), call_usage)
    usage.add(call_usage)
    return response


def _run_steps(messages: list, workspace: Path, settings: Settings, usage: Usage, meter: ContextMeter) -> None:
    tools = agent_tools(settings)
    reads = ReadTracker()
    for step in range(settings.max_steps):
        if ensure_room(messages, settings, usage, meter, tools):
            reads.clear()
        tool_choice = "auto"
        if step == 0 and settings.explore_mode == "always":
            tool_choice = {"type": "function", "function": {"name": EXPLORE_TOOL_NAME}}
        response_msg = _call_model(messages, tools, settings, usage, meter, tool_choice, reads)
        messages.append(response_msg)

        content = response_msg.get("content") or ""
        tool_calls = response_msg.get("tool_calls") or []
        if not tool_calls:
            print(f"\nAgent > {sanitize(content) or '(no response)'}\n")
            return
        if content:
            print(f"\nAgent > {sanitize(content)}\n")

        for index, call in enumerate(tool_calls):
            function = call.get("function") or {}
            name = function.get("name") or ""
            raw_args = function.get("arguments")
            print(f"[Tool Call] {sanitize(name)}({sanitize(clip(str(raw_args), 200))})")
            try:
                if name == EXPLORE_TOOL_NAME and settings.explore_mode != "never":
                    result = run_explore(raw_args, workspace, settings, usage)
                else:
                    result = reads.dispatch(name, raw_args, workspace)
            except KeyboardInterrupt as interrupt:
                # An interrupted explore still reports what it had looked at.
                messages.append(tool_result_message(call, getattr(interrupt, "result", None) or CANCELLED_RESULT))
                for pending in tool_calls[index + 1:]:
                    messages.append(tool_result_message(pending, CANCELLED_RESULT))
                raise
            if result.get("status") != "success":
                print(f"  -> {result.get('status')}: {sanitize(clip(str(result.get('message', '')), 200))}")
            messages.append(tool_result_message(call, result))

    print(f"\n[Stopped] Reached the limit of {settings.max_steps} steps for one request. "
          "Send another message to let the agent continue.\n")


def run_turn(messages: list, workspace: Path, settings: Settings, meter: ContextMeter = None,
             session: Usage = None) -> None:
    """
    Alternates model calls and tool calls until the model answers without tools,
    or the step limit is reached. On KeyboardInterrupt every tool call the model
    already requested gets a result, so the history stays valid for the next request.
    Token usage for the request is printed at the end, however it ends, and added to `session`.
    """
    usage = Usage()
    try:
        _run_steps(messages, workspace, settings, usage, meter or ContextMeter())
    finally:
        if usage.calls:
            print(usage.summary() + "\n")
        if session is not None:
            session.merge(usage)


def _discard_unanswered(messages: list, user_input: str) -> bool:
    """
    Drops the user's message if nothing happened after it, so retrying doesn't send it twice.
    Compares content too: after compaction the last message may be a summary, which must stay.
    """
    if messages and messages[-1] == {"role": "user", "content": user_input}:
        messages.pop()
        return True
    return False


def _context_line(messages: list, settings: Settings, meter: ContextMeter) -> str:
    size = meter.estimate(messages, agent_tools(settings))
    return f"[Context] ~{size:,} of {settings.context_limit:,} tokens ({size * 100 // settings.context_limit}%)"


def run_command(line: str, messages: list, settings: Settings, meter: ContextMeter, session: Usage) -> bool:
    """Handles a /command typed at the prompt. Returns False if the line is not a known command."""
    command, _, argument = line.partition(" ")
    command = command.lower()
    if command == "/help":
        print(COMMANDS_HELP + "\n")
    elif command == "/usage":
        print(session.summary("[Session]") if session.calls else "[Session] No model calls yet.")
        print(_context_line(messages, settings, meter) + "\n")
    elif command == "/compact":
        usage = Usage()
        before = _context_line(messages, settings, meter)
        try:
            compacted = compact_history(messages, settings, usage, keep_steps=0, mid_request=False,
                                        instructions=argument.strip())
        except KeyboardInterrupt:
            print("\n[Interrupted] The conversation was not changed.\n")
            return True
        except LLMError as e:
            print(f"[Error] Compaction failed, the conversation was not changed: {e}\n", file=sys.stderr)
            return True
        finally:
            session.merge(usage)
        if compacted:
            meter.reset()
            print(f"{before}\n -> after compacting: {_context_line(messages, settings, meter)[len('[Context] '):]}\n")
        else:
            print("Nothing to compact yet.\n")
    else:
        return False
    return True


def run_agent(workspace: Path, settings: Settings) -> None:
    system_prompt, agents_status = build_system_context(workspace, settings.explore_mode)
    messages = [{"role": "system", "content": system_prompt}]
    meter, session = ContextMeter(), Usage()

    print("=" * 60)
    print(f"Directory Sandbox : {workspace.resolve()}")
    print("Shell Disabled    : True (Pure Python file APIs only)")
    print(f"AGENTS.md         : {agents_status}")
    print(f"Model             : {settings.model}")
    print(f"Context Limit     : {settings.context_limit:,} tokens (auto-compacts near the limit)")
    explore = "off" if settings.explore_mode == "never" else f"{settings.explore_mode}, {settings.explore_model or settings.model}"
    print(f"Explore           : {explore}")
    if settings.log_path:
        print(f"Usage Log         : {settings.log_path}")
    print("Type /help for commands.")
    print("=" * 60 + "\n")

    while True:
        try:
            user_input = input("You > ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nExiting.")
            break

        if not user_input:
            continue
        if user_input.lower() in ("exit", "quit"):
            break
        if user_input.startswith("/") and run_command(user_input, messages, settings, meter, session):
            continue

        elided = elide_stale_tool_results(messages)
        if elided:
            meter.reset()
            print(f"[Context] Elided {elided} bulky tool output{'s' if elided != 1 else ''} from older requests.")
        messages.append({"role": "user", "content": user_input})
        try:
            run_turn(messages, workspace, settings, meter, session)
        except KeyboardInterrupt:
            print("\n[Interrupted]")
        except LLMError as e:
            print(f"\n[Error] {e}", file=sys.stderr)
        else:
            continue
        if _discard_unanswered(messages, user_input):
            print("Your last message was not sent; enter it again to retry.\n")
        else:
            print("Progress so far is kept; send a message to continue.\n")

    if session.calls:
        print(session.summary("[Session]"))


# ==================== chippy/__main__.py ====================

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="chippy",
        description="Zero-dependency Sandboxed Agent Runner",
        epilog=f"The API key is read from the {API_KEY_ENV} environment variable.",
    )
    parser.add_argument("-d", "--dir", default=".", help="Target directory to lock the harness to.")
    parser.add_argument("-m", "--model", default=DEFAULT_MODEL, help="Model name.")
    parser.add_argument("--url", default=DEFAULT_URL, help="Chat completions endpoint URL.")
    parser.add_argument("--temperature", type=float, default=None,
                        help="Sampling temperature. Omitted from requests when not set.")
    parser.add_argument("--max-steps", type=int, default=DEFAULT_MAX_STEPS,
                        help="Maximum model calls per message before the agent pauses.")
    parser.add_argument("--explore-model", default=DEFAULT_EXPLORE_MODEL,
                        help="Model for the explore sub-agent, e.g. a cheaper one. Defaults to --model "
                             "(or the LLM_EXPLORE_MODEL environment variable).")
    parser.add_argument("--explore-max-steps", type=int, default=DEFAULT_EXPLORE_MAX_STEPS,
                        help="Maximum model calls for one explore run before it must report back.")
    parser.add_argument("--explore", choices=EXPLORE_MODES, default="auto",
                        help="auto: the agent decides when to explore; always: every request starts with "
                             "an explore; never: no explore tool.")
    parser.add_argument("--context-limit", type=int, default=os.getenv("LLM_CONTEXT_LIMIT", DEFAULT_CONTEXT_LIMIT),
                        help="The model's context window in tokens; the conversation is compacted automatically "
                             f"as it gets close (default {DEFAULT_CONTEXT_LIMIT:,}, or LLM_CONTEXT_LIMIT).")
    parser.add_argument("--log", default="", metavar="PATH",
                        help="Append one JSON line per model call (source, model, token usage) to this file.")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")

    args = parser.parse_args(argv)
    if args.max_steps < 1:
        parser.error("--max-steps must be at least 1")
    if args.explore_max_steps < 1:
        parser.error("--explore-max-steps must be at least 1")
    if args.context_limit < MIN_CONTEXT_LIMIT:
        parser.error(f"--context-limit must be at least {MIN_CONTEXT_LIMIT:,}")

    target_dir = Path(args.dir).resolve()
    if not target_dir.is_dir():
        print(f"Error: Scoped folder '{target_dir}' does not exist.", file=sys.stderr)
        return 1

    settings = Settings(
        model=args.model,
        url=args.url,
        api_key=os.getenv(API_KEY_ENV, ""),
        temperature=args.temperature,
        max_steps=args.max_steps,
        explore_model=args.explore_model,
        explore_max_steps=args.explore_max_steps,
        explore_mode=args.explore,
        context_limit=args.context_limit,
        log_path=args.log,
    )
    run_agent(target_dir, settings)
    return 0


if __name__ == "__main__":
    sys.exit(main())
